plugins {
    id 'java'
    id 'sktools.wsimport'
}

configurations {
    wsdls
}

dependencies {
    wsdls project(path: ':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wswar', configuration: 'wsdls')
    jaxws libraries.jaxws_tools

    implementation libraries.jaxws_rt
}

// https://discuss.gradle.org/t/right-way-to-copy-contents-from-dependency-archives/7449/13
task importWsdls(type: Sync) {
    dependsOn configurations.wsdls

    into('META-INF/wsdls/skif-wsversioning-v2') {
        from { configurations.wsdls.collect { zipTree(it) } }
    }

    into "$buildDir/wsdls/"
}

processResources.dependsOn importWsdls
sourceSets.main.resources.srcDir importWsdls.destinationDir

wsimport {
    exceptionReusePackage 'no.statkart.skif.wsversioning.wsapi.v2.exception'
}
