apply plugin: 'java'
apply plugin: 'sktools-weblogic-wsclient-plugin'

dependencies {
    weblogicProvided project(':skif-config') // For å tvinge bruk av JAX-WS RI og JAXB RI
    weblogicProvided libraries.weblogic
    weblogicProvided libraries['tools.jar']
}

weblogicWsClient {
    webService {
        baseWar {
            project(path: ':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wswar', configuration: 'wsdls')
        }
        exceptionReusePackage 'no.statkart.skif.wsversioning.wsapi.v2.exception'
    }
}


