plugins {
    id 'java-library'
}

/**
 * Denne modulen blir konsumert i to kombinasjoner
 *
 * 1. Server mode :: wsmapping + wsschema
 * 2. Client mode :: wsmapping + wsclient
 * 3. SingleVm    :: samme som server mode
 */


dependencies {
    api project(':skif-store-test:skif-store-test-api')
    compileOnly project(':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wsschema')
    // Trengs for Java 11 får å unngå 'warning: unknown enum constant XmlAccessType.FIELD'
    api libraries.jaxb_api

    testImplementation project(':skif-testsupport-common')
    testImplementation project(':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wsschema')

    //internal dependencies + optional deps to logging frameworks:
    testImplementation project(':skif-config')

}
