apply plugin: 'java-library'

dependencies {
    api project(':skif-store-test:skif-store-test-api')
    api project(':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wsschema')

    testImplementation project(':skif-testsupport-common')

    //internal dependencies + optional deps to logging frameworks:
    testImplementation project(':skif-config')

}