plugins {
    id 'java-library'
    id 'sktools.provided'
}

/**
 * Denne modulen blir konsumert i to kombinasjoner
 *
 * 1. Server mode :: wsmapping + wsschema
 * 2. Client mode :: wsmapping + wsclient
 * 3. SingleVm    :: samme som server mode
 */


dependencies {
    api project(':skif-store-test:skif-store-test-api')
    provided project(':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wsschema')

    testImplementation project(':skif-testsupport-common')

    //internal dependencies + optional deps to logging frameworks:
    testImplementation project(':skif-config')

}