plugins {
    id 'java-library'
    id 'sktools.provided'
}

dependencies {
    api project(':skif-wsversioning:skif-wsversioning-api')
    provided project(':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wsschema')

    testImplementation project(':skif-testsupport-common')

    //internal dependencies + optional deps to logging frameworks:
    testImplementation project(':skif-config')
}