apply plugin: 'java'

dependencies {
    compile project(':skif-wsversioning:skif-wsversioning-api')
    provided project(':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wsschema')

    testCompile project(':skif-testsupport-common')

    //internal dependencies + optional deps to logging frameworks:
    testCompile project(':skif-config')

}