apply plugin: 'maven'

dependencies {
     compile project(':skif-service-common')

    testCompile project(':skif-config')
    testCompile project(':skif-testsupport-common')

}

task testJar(type: Jar) {
    classifier = 'tests'
    from sourceSets.test.classes
}

configurations {
    testApi
}

artifacts {
    testApi testJar
}