apply plugin: 'java-library'
apply plugin: 'maven-publish'

description = 'Inneholder Store funksjonalitet samt mulighet for remote service kall (via transitiv dependency skif-service-common)'

configurations {
    testApi
}

dependencies {
//    api libraries.guava

    implementation project(':skif-service-common')
    implementation libraries.guava

    testImplementation project(':skif-config')
    testImplementation project(':skif-testsupport-common')

    testImplementation libraries.reflections

}

task testJar(type: Jar) {
    classifier = 'tests'
    from sourceSets.test.output
}

task sourcesJar(type: Jar, dependsOn:classes) {
    classifier = 'sources'
    from sourceSets.main.allSource
}

artifacts {
    testApi testJar
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact sourcesJar
        }
    }
}

task assertDependencies() {
    doFirst {
        configurations.runtime.copyRecursive{it instanceof ExternalDependency}.dependencies.each { Dependency dependency ->
            boolean godkjent = [ //liste over dependencies. For syntax se parsing under..
                    'org.slf4j',
                    'com.google.code.findbugs:jsr305',
                    'com.google.inject:guice',
                    'com.google.inject.extensions:guice-',
                    'com.google.guava',
                    'com.vividsolutions:jts',
            ].find { "${dependency.group}:${dependency.name}:${dependency.version}".startsWith(it) }

            if (!godkjent) {
                throw new TaskExecutionException(it, new RuntimeException('Ukjent avhengighet: ' + dependency)); //avhengighet ikke i godkjent-liste
            }
        }
    }
}
test.dependsOn assertDependencies //kjøres som en test
test.dependsOn assertDependencies //kjøres som en test
