plugins {
    id 'java-library'
    id 'maven-publish'
}

description = 'Inneholder Store funksjonalitet samt mulighet for remote service kall (via transitiv dependency skif-service-common)'

configurations {
    testApi
}

dependencies {
    api project(':skif-service-common')
    api libraries.bubbleref_spi
    implementation libraries.guava

    testImplementation project(':skif-config')
    testImplementation project(':skif-testsupport-common')

    testImplementation libraries.reflections

}

task testJar(type: Jar) {
    archiveClassifier = 'tests'
    from sourceSets.test.output
}

artifacts {
    testApi testJar
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}

task assertDependencies() {
    doFirst {
        configurations.runtimeElements.copyRecursive{it instanceof ExternalDependency}.dependencies.each { Dependency dependency ->
            boolean godkjent = [ //liste over dependencies. For syntax se parsing under..
                    'org.slf4j',
                    'com.google.code.findbugs:jsr305',
                    'com.google.inject:guice',
                    'com.google.inject.extensions:guice-',
                    'com.google.guava',
                    'no.statkart.skif:skif-bubble-spi'
            ].find { "${dependency.group}:${dependency.name}:${dependency.version}".startsWith(it) }

            if (!godkjent) {
                throw new TaskExecutionException(it, new RuntimeException('Ukjent avhengighet: ' + dependency)) //avhengighet ikke i godkjent-liste
            }
        }
    }
}
test.dependsOn assertDependencies //kjøres som en test
