version: 2
registries:
    github-sktools:
        type: maven-repository
        url: https://maven.pkg.github.com/kartverket/SkTools
        username: x-access-token
        password: ${{ secrets.SHARED_PACKAGES_READ_TOKEN }}

updates:
    - package-ecosystem: 'github-actions'
      directory: '.github/workflows'
      schedule:
          interval: 'weekly'
          time: '07:00'
          timezone: 'Europe/Oslo'
      groups:
          marocchino:
            patterns:
               - "marocchino/*"
          github-actions:
            patterns:
               - "actions/*"
    - package-ecosystem: "gradle"
      directory: "/"
      open-pull-requests-limit: 20
      registries:
          - github-sktools
      schedule:
          interval: "weekly"
          time: '07:00'
          timezone: 'Europe/Oslo'
      ignore:
          - dependency-name: "gradle"
            update-types: ["version-update:semver-major"]
          # Jakarta EE
          - dependency-name: "jakarta.*"
            update-types: ["version-update:semver-major", "version-update:semver-minor"]
          # Jakarta EE Web services
          - dependency-name: "com.sun.xml.ws:*"
            update-types: ["version-update:semver-major", "version-update:semver-minor"]
          # Jakarta EE JAXB
          - dependency-name: "com.sun.xml.bind:*"
            update-types: ["version-update:semver-major"]
          - dependency-name: "org.glassfish.jaxb:*"
            update-types: ["version-update:semver-major"]
            
          # Jakarta EE Application server
          - dependency-name: "org.apache.cxf:*"
            update-types: ["version-update:semver-major", "version-update:semver-minor"]
          - dependency-name: "org.apache.tomcat:*"
            update-types: ["version-update:semver-major"]
          - dependency-name: "org.apache.tomee:*"
            update-types: ["version-update:semver-major"]
