apply plugin: 'ear'

Map warMap = [
        ':skif-store-test:skif-store-test-wswar': 'storetest/wsapi',
]

List ejbList = [
        ':skif-store-test:skif-store-test-server'
]

dependencies {
    ejbList.each {
        deploy project(it)
    }
    warMap.each {
        deploy project(it.key)
    }
    (ejbList + warMap.keySet()).each {
        earlib project(it)
    }

    // TODO: Bør noen av de andre modulene trekke med seg denne (de har den nå på testCompile)?
    earlib project(':skif-config')
}

ear {
    libDirName 'APP-INF/lib'
    deploymentDescriptor {
        version = "5"
        displayName= "skif-store-test"
        warMap.each {
            def p = project(it.key)
            webModule(p.name + '-' + p.version + ".war", it.value)
        }
    }
}

ant.taskdef(name: 'wldeploy', classname: 'weblogic.ant.taskdefs.management.WLDeploy', classpath: configurations.weblogic.asPath)

task deploy(dependsOn: 'assemble') << {
    wlsDeployProtocol = "${wls_deploy_protocol}"
    wlsDeployIp = "${wls_deploy_hostname}"
    wlsDeployPort = "${wls_deploy_port}"
    wlsAdminUrl = "${wlsDeployProtocol}://${wlsDeployIp}:${wlsDeployPort}"
    wlsDeployTargets = "${wls_deploy_targets}"
    wlsDeployUsername = "${wls_username}"
    wlsDeployPassword = "${wls_password}"

    ant.wldeploy(action: 'deploy', source: "${ear.archivePath}", name: project.name, user: wlsDeployUsername, password: wlsDeployPassword,
                 adminurl: wlsAdminUrl, targets: wlsDeployTargets, upload: 'true', timeout: '18000', verbose: 'true', failonerror: 'true')
}

task undeploy << {
    wlsDeployProtocol = "${wls_deploy_protocol}"
    wlsDeployIp = "${wls_deploy_hostname}"
    wlsDeployPort = "${wls_deploy_port}"
    wlsAdminUrl = "${wlsDeployProtocol}://${wlsDeployIp}:${wlsDeployPort}"
    wlsDeployTargets = "${wls_deploy_targets}"
    wlsDeployUsername = "${wls_username}"
    wlsDeployPassword = "${wls_password}"

    ant.wldeploy(action: 'undeploy', name: project.name, user: wlsDeployUsername, password: wlsDeployPassword,
            adminurl: wlsAdminUrl, targets: 'AdminServer', graceful: true, verbose: true, failonerror: true)
}
