plugins {
    id 'java-library'
    id 'skif-provided'
}

java {
    registerFeature('singlevm') {
        usingSourceSet(sourceSets.main)
    }
}

configurations {
    provided {
        description = 'Dependencies for compiling and single-vm'
    }

    singlevmImplementation.extendsFrom provided
}
