assert ['1.0', '1.1'].contains(gradle.gradleVersion)

apply plugin: 'sktools-filterproperties-plugin'

//user properties
Map userProperties = propertyUtils.fromFile('gradle-user.properties') << gradle.startParameter.projectProperties
propertyUtils.assignPropertiesToProject(userProperties)


allprojects {
    apply plugin: 'sktools-filterproperties-plugin'
    propertyUtils.assignPropertiesToProject(userProperties)

    //version kan bestemmes via env variabel og -P parameter
    if (project.hasProperty('version')) { version = getProperty('version') }

    defaultTasks 'build'
    group = 'no.statkart.skif'


    apply plugin: 'idea'
    apply plugin: 'sktools-ideaextensions-plugin'


    repositories {
        if (MAVEN_LOCAL_FOR_PROJECT) {
            println '...initializing MAVEN_LOCAL_FOR_PROJECT'
            mavenLocal()
        }
        mavenRepo name: 'public', url: MAVEN_REPO

        if (!MAVEN_LOCAL_FOR_PROJECT) {
            mavenLocal()
        }
    }

}

// Optional configuration of library versions to use.
// Simply add version properties to your gradle-user.property file to use this feature.
def libVersion(String name, String defaultValue) {
    project.ext.properties.get('version.' + name, defaultValue) //development mode only
}

// build a map of the dependency artifacts to use. Allows centralized definition of the versions of artifacts to
// use. In that respect it serves a role similar to <dependencyManagement> in Maven
def libraries = [

        // Tools
        'tools.jar': files("${System.getenv('JAVA_HOME')}/lib/tools.jar").stopExecutionIfEmpty(), //JAVA_HOME ikke satt??

        // Database
        // TODO: Legge inn støtte for å kunne velge mellom debug og produksjonsversjon
        ojdbc: "com.oracle:ojdbc6_g:${libVersion('oracle', '11.2.0.2.0')}@jar",

        // Logging 
        slf4j_api: "org.slf4j:slf4j-api:${libVersion('slf4j', '1.6.1')}@jar",
        jcl_to_slf4j: "org.slf4j:jcl-over-slf4j:${libVersion('slf4j', '1.6.1')}@jar",
        jul_to_slf4j: "org.slf4j:jul-to-slf4j:${libVersion('slf4j', '1.6.1')}@jar",
        log4j_to_slf4j: "org.slf4j:log4j-over-slf4j:${libVersion('slf4j', '1.6.1')}@jar",
        logback_classic: "ch.qos.logback:logback-classic:${libVersion('logback', '0.9.28')}@jar",
        logback_core: "ch.qos.logback:logback-core:${libVersion('logback', '0.9.28')}@jar",

        // Guice med extensions
        guice: "com.google.inject:guice:${libVersion('guice', '3.0')}",
        guice_multibindings: "com.google.inject.extensions:guice-multibindings:${libVersion('guice', '3.0')}",
        guice_throwingproviders: "com.google.inject.extensions:guice-throwingproviders:${libVersion('guice', '3.0')}",
        guice_assistedinject: "com.google.inject.extensions:guice-assistedinject:${libVersion('guice', '3.0')}",
        guice_grapher: "com.google.inject.extensions:guice-grapher:${libVersion('guice', '3.0')}",
        // guice-servlet depends on servlet-api som her er provided via weblogic og derfor ikke skal være med her
        guice_servlet: "com.google.inject.extensions:guice-servlet:${libVersion('guice', '3.0')}@jar",

        jsr330: "javax.inject:javax.inject:1",

        // Utility libraries
        guava: "com.google.guava:guava:11.0.1",
        jsr305: "com.google.code.findbugs:jsr305:1.3.9",

        // Testing
        testng: 'org.testng:testng:6.0.1',
        mockito: 'org.mockito:mockito-all:1.9.5',
        dbunit: 'org.dbunit:dbunit:2.4.8@jar',
        unitils: 'org.unitils:unitils-core:3.1',
        fest: 'org.easytesting:fest-assert-core:2.0M8',
        reflections: 'org.reflections:reflections:0.9.8',

        // JAXB
        jaxb_impl: "com.sun.xml.bind:jaxb-impl:${libVersion('jaxb', '2.1.13')}",
        jaxb_xjc: "com.sun.xml.bind:jaxb-xjc:${libVersion('jaxb', '2.1.13')}",

        jts: "com.vividsolutions:jts:${libVersion('jts', '1.7.1')}",

        //Commons-lang 2.5
        commons_lang: "org.apache.commons:commons-lang3:3.1",

]

// JAX-WS runtime for weblogic
libraries.jaxws_rt = files(
        files(isWeblogic10310() ? "${WEBLOGIC_HOME}/modules/glassfish.jaxws.rt_1.0.0.0_2-1-4.jar" :
            "${WEBLOGIC_HOME}/modules/glassfish.jaxws.rt_1.2.0.0_2-1-5.jar"),
)

boolean isWeblogic10310() {
    new File("${WEBLOGIC_HOME}/utils/config/10.3.1.0/".toString()).exists()
}

// Weblogic jar files must be located in the WEBLOGIC_HOME directory since they internally (in their manifest file) refer to other files in the directory
libraries.weblogic = files(
        "${WEBLOGIC_HOME}/wlserver_10.3/server/lib/weblogic.jar",
        "${WEBLOGIC_HOME}/wlserver_10.3/server/lib/webservices.jar",
        "${WEBLOGIC_HOME}/wlserver_10.3/server/lib/wljmsclient.jar",
        isWeblogic10310() ? "${WEBLOGIC_HOME}/modules/javax.annotation_1.1.jar/" :
            "${WEBLOGIC_HOME}/modules/javax.annotation_1.0.0.0_1-0.jar/",
        "${WEBLOGIC_HOME}/modules/javax.ejb_3.0.1.jar",
        "${WEBLOGIC_HOME}/modules/javax.interceptor_1.0.jar",
        "${WEBLOGIC_HOME}/modules/javax.servlet_1.0.0.0_2-5.jar",
        "${WEBLOGIC_HOME}/modules/javax.transaction_1.0.0.0_1-1.jar",
        isWeblogic10310() ? "${WEBLOGIC_HOME}/modules/com.bea.core.transaction_2.5.1.0.jar" :
            "${WEBLOGIC_HOME}/modules/com.bea.core.transaction_2.7.0.0.jar",
        isWeblogic10310() ? "${WEBLOGIC_HOME}/modules/com.bea.core.datasource6_1.6.0.0.jar" :
            "${WEBLOGIC_HOME}/modules/com.bea.core.datasource6_1.9.0.0.jar",
        libraries.jaxws_rt,
        "${WEBLOGIC_HOME}/modules/com.bea.core.utils.wrapper_1.4.0.0.jar",
        isWeblogic10310() ? "${WEBLOGIC_HOME}/modules/com.bea.core.resourcepool_1.5.0.0.jar": "${WEBLOGIC_HOME}/modules/com.bea.core.resourcepool_1.7.0.0.jar" ,
)
libraries.gt2 = [
        'org.geotools:gt2-oracle-spatial:2.2.2-CUSTOM@jar',
]

libraries.guice_with_used_deps = [
        libraries.guice,
        libraries.guice_multibindings,
        libraries.guice_throwingproviders,
        libraries.guice_assistedinject,
        libraries.guice_servlet,
        libraries.jsr330,
]

libraries.hibernate_3_2 = [
        'antlr:antlr:2.7.6@jar',
        'cglib:cglib-nodep:2.2@jar',
        'dom4j:dom4j:1.4@jar',
        'net.sf.ehcache:ehcache:1.2.3@jar',
        'odmg:odmg:3.0@jar',
        "org.hibernate:hibernate:3.2.6.GA-bubbleref-v2@jar",
        libraries.ojdbc,
]

libraries.hibernate_tools_3_2 = [
        "org.hibernate:hibernate-tools:3.2.6.GA@jar",
]

libraries.hibernate_3_6 = [
        'org.hibernate:hibernate-parent:3.6.10.Final',
        'org.hibernate:hibernate-core:3.6.10.Final.bubbleref.v1',
        'commons-collections:commons-collections:3.1',
        'dom4j:dom4j:1.6.1@jar',
        'org.hibernate:hibernate-commons-annotations:3.2.0.Final',
        'org.hibernate.javax.persistence:hibernate-jpa-2.0-api:1.0.1.Final',
        'javax.transaction:jta:1.1',
        'org.antlr:antlr:3.4@jar',
        'net.sf.ehcache:ehcache-core:2.5.2',
        'odmg:odmg:3.0@jar',
        'javassist:javassist:3.12.1.GA',
        libraries.ojdbc,
]


subprojects { Project project ->
    apply plugin: 'idea'
    apply plugin: 'project-report'
    apply plugin: 'base'

    sourceCompatibility = '1.6'
    targetCompatibility = '1.6'

    configurations {
        weblogic {
            description = 'Weblogic dependencies'
        }

        provided {
            description = 'Provided dependencies not to be included in dependencies'
        }
    }

    dependencies {
        weblogic libraries.weblogic
    }

    clean {
        delete 'gen'
    }

    propertyUtils.expandProjectProperties() //må ekspanderes i alle prosjekter da det kun er initielle build.properties + ifra kommandolinjen som blir arvet...
    //PS: dersom 'version' eller andre properties ønskes overstyrt i underprosjekter må disse evaluerest først. (evt kan man legge denne til en afterEvaluate{})

    if (!['-ear', '-wswar'].find {project.name.endsWith(it)}) {
        apply plugin: 'java'
        apply plugin: 'sktools-filterproperties-plugin'

        test.testLogging.showStandardStreams = true

        //user properties
        project.filterProperties {
            Map filterProperties = propertyUtils.fromFile("${project.name}-filter.properties") << gradle.startParameter.projectProperties
            propertyUtils.expandProperties(filterProperties)

//            println "filterprops: ${filterProperties}" //debug
            properties filterProperties
        }

        project.ext.set('libraries', libraries) //eksponerer denne for alle prosjekter

        // appropriately inject the common dependencies into each sub-project
        dependencies {
            compile libraries.slf4j_api
            compile libraries.jsr305

            testCompile libraries.testng
            testCompile libraries.mockito
            testCompile libraries.fest
            testRuntime 'org.uncommons:reportng:1.1.3'
            testRuntime 'velocity:velocity-dep:1.4'
        }

        sourceSets {
            main.compileClasspath += configurations.provided
            test.compileClasspath += configurations.provided
            test.runtimeClasspath += configurations.provided
        }

        project.idea.module {
            // Får Idea til å legge build katalog for alle moduler i en egen felles topp katalog (out/production, out/test)
            inheritOutputDirs = true
            scopes.PROVIDED.plus += configurations.provided
        }

        test {
            // Vi ønsker som default å stoppe ved første modul som feiler.
            ignoreFailures = false

            boolean singleVm = Boolean.valueOf(rootProject.properties['single_vm'])
            logger.debug "single_vm is set to ${singleVm} for ${project.path}"

            useTestNG() {
                excludeGroups('broken')
                if (singleVm) {
                    excludeGroups('server-required')
                } else {
                    excludeGroups('singlevm-required')
                }
            }

            jvmArgs '-Xmx1024m'
            if (rootProject.hasProperty('test.remote.debug')) {
                jvmArgs '-Xdebug'
                jvmArgs '-Xnoagent'
                jvmArgs '-Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=y'
            }

            //listening to test execution events
            afterTest { descriptor, result ->
                logger.lifecycle("${result.toString() == 'SUCCESS' ? ' Sucessfully tested' : 'Failed testing'} : ${descriptor.className}#${descriptor.name}")
                if (result.resultType.name() == 'FAILURE') {
                    logger.error("${result.exception}")
                }
            }

        }

        afterEvaluate {
            //kobler inn standard upload repositores ved bruk av maven plugin
            if (plugins.hasPlugin('maven')) {
                uploadArchives.repositories.mavenDeployer {
                    repository(url: uri(REPO_UPLOAD_RELEASES)) {
                        authentication([userName: REPO_UPLOAD_RELEASES_USERNAME, password: REPO_UPLOAD_RELEASES_PASSWORD])
                    }
                    snapshotRepository(url: uri(REPO_UPLOAD_SNAPSHOTS)) {
                        authentication([userName: REPO_UPLOAD_SNAPSHOTS_USERNAME, password: REPO_UPLOAD_SNAPSHOTS_PASSWORD])
                    }
                }
            }
        }

        tasks.ideaModule {

            // Plasserer weblogic avhengigheter til sist på classpath...
            doFirst {
                def weblogic_home = project.WEBLOGIC_HOME.replace('\\', '/').toLowerCase()

                project.idea.module.iml.withXml { provider ->
                    def rootNode = provider.asNode()
                    def node = rootNode.component.find {it.@name == 'NewModuleRootManager'}

                    def weblogicNodes = node.orderEntry.findAll {
                        it.@type.equals('module-library') && it.library.CLASSES.root.@url.findAll({ it.toLowerCase().contains(weblogic_home) }).size() > 0
                    }

                    weblogicNodes.each { node.remove it }
                    weblogicNodes.each { node.append it }
                }
            }

        }

        //todo
//        Source is in the build directory so we need to unexclude it
//        GradleUtil.makeIdeaShowBuildDirectory(project)
    }
}

afterEvaluate {

    idea.project {
        jdkName = '1.6'
        languageLevel = '1.6'

        ipr {
            //adding Perforce as default vcs by tinkering with the output *.ipr file before it's written out
            withXml {
                def node = it.asNode()
                def component = node.appendNode('component', ['name': 'VcsDirectoryMappings'])
                component.appendNode('mapping', ['directory': '', 'vcs': 'Perforce'])
            }
        }
    }

    println "project.version = ${project.getVersion()}"
    println "project.version = ${project.version}"
    println "project.version = ${version}"

    // branch spesifike navn for prosjekt og workspace fil.
    ideaWorkspace {
        outputFile = file("${project.name}-${project.version.toString().replace('-SNAPSHOT', '')}.iws")
    }
    idea.project {
        outputFile = file("${project.name}-${project.version.toString().replace('-SNAPSHOT', '')}.ipr")
    }

}


buildscript {

    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Env variabler til bruk ved utvikling mot lokalt Maven Repository
    //  - Disse styrer også repository som blir brukt til å uploade artifakter
    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    [
            'MAVEN_REPO',
            'REPO_UPLOAD_RELEASES',
            'REPO_UPLOAD_RELEASES_USERNAME',
            'REPO_UPLOAD_RELEASES_PASSWORD',
            'REPO_UPLOAD_SNAPSHOTS',
            'REPO_UPLOAD_SNAPSHOTS_USERNAME',
            'REPO_UPLOAD_SNAPSHOTS_PASSWORD',
    ].each { key ->
        if (!project.hasProperty(key)) {
            throw new GradleException("Mandatory env variable ORG_GRADLE_PROJECT_${key} not set!")
        }
    }

    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Påkrevde env variable
    // Disse kan bli satt via env variabler eller via gradle.properties i gradle user home dir
    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    ['WEBLOGIC_HOME'].each { key ->
        if (!project.hasProperty(key)) {
            throw new GradleException("Mandatory env variable ORG_GRADLE_PROJECT_${key} not set!")
        }
    }

    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Switch for tentativ utvikling mot lokalt maven repository
    // Se http://forums.gradle.org/gradle/topics/dependency_resolution_in_gradle_1_0_milestone_8 for teknisk beskrivelse.
    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    project.ext.set('MAVEN_LOCAL_FOR_BUILDSYSTEM', (Boolean.parseBoolean(System.getenv('MAVEN_LOCAL')) || Boolean.parseBoolean(System.getenv('MAVEN_LOCAL_FOR_BUILDSYSTEM'))) ? true : null)
    project.ext.set('MAVEN_LOCAL_FOR_PROJECT', (Boolean.parseBoolean(System.getenv('MAVEN_LOCAL')) || Boolean.parseBoolean(System.getenv('MAVEN_LOCAL_FOR_PROJECT'))) ? true : null)


    repositories {
        if (MAVEN_LOCAL_FOR_BUILDSYSTEM) {
            println '...initializing MAVEN_LOCAL_FOR_BUILDSYSTEM'
            mavenLocal()
        }
        mavenRepo name: 'public', url: MAVEN_REPO

        if (!MAVEN_LOCAL_FOR_BUILDSYSTEM) {
            mavenLocal()
        }
    }

    dependencies {
        classpath 'no.statkart.sktools.gradle:gradle-plugins:1.2-build86'
    }
}
