skif.single_vm=true

skif.server_username=frehen
skif.server_password=matr57stat
skif.server_url=https://localhost:7002

skif.db_hostname=wsfrehen1
skif.db_sid=HFDEV
skif.db_port=1521
skif.db_username=frehen
skif.db_password=frehen1

