# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: Component
metadata:
  name: "skif"
  description: "Statens kartverk sitt felles egenutviklede rammeverk for informasjons-systemer"
  tags:
    - "public"
spec:
  type: library
  lifecycle: production
  owner: heimdall
