#defines properties for resource substitution

skif.single_vm=${single_vm}

skif.server_username=${skif.server_username}
skif.server_password=${skif.server_password}
skif.server_url=${skif.server_url}

skif.db_hostname=${db_hostname}
skif.db_sid=${db_sid}
skif.db_port=${db_port}
skif.db_username=${db_username}
skif.db_password=${db_password}
skif.db_history_schema_name=${db_history_schema_name}
skif.db_non_history_schema_name=${db_non_history_schema_name}