hibernateVersion=3.2

single_vm=true

skif.server_username=frehen
skif.server_password=matr57stat
skif.server_url=https://${wls_server}


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! Database configuration
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
db_username=<not set>
db_password=${db_username}
db_sid=MA01TST
db_hostname=SKRIVDB03
db_port=1521

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! Application server configuration - weblogic
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
wls_username=admmatr
wls_password=matrikkeladm1

wls_hostname=${COMPUTERNAME}.statkart.no
wls_port=7001
wls_sport=7002
wls_server=${wls_hostname}:${wls_sport}

wls_deploy_targets=AdminServer
wls_deploy_hostname=${wls_hostname}
wls_deploy_protocol=http
wls_deploy_port=${wls_port}
