hibernateVersion=3.2

single_vm=true

skif.server_username=<not set>
skif.server_password=<not set>
skif.server_url=https://${wls_server}


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! Database configuration
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
db_username=<not set>
db_password=${db_username}
db_sid=MA01TST
db_hostname=SKRIVDB03
db_port=1521

db_lock_tablename=LOCKINFO
db_sequence_tablename=TABLESEQUENCE

# Systembruker/password som brukes ved database administrasjon, create.user, export/import etc.    cd
admin_db_username=SYSTEM
admin_db_password=MATRIKKELADM


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! Application server configuration - weblogic
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
wls_username=admmatr
wls_password=matrikkeladm1

wls_hostname=${LOCALHOSTNAME}
wls_port=7001
wls_sport=7002
wls_server=${wls_hostname}:${wls_sport}

wls_deploy_targets=AdminServer
wls_deploy_hostname=${wls_hostname}
wls_deploy_protocol=http
wls_deploy_port=${wls_port}

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! Libraries and versions
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
version.buildUtils=1.0
version.hibernate=3.2.6.GA
version.jaxb=2.1.13
version.logback=0.9.28
version.slf4j=1.6.1
version.oracle=11.2.0.2.0
version.guice=3.0
version.jts=1.7.1
version.gt2_oracle_spatial=2.2.2
