single_vm=true
#single_vm=false


skif.server_username=testUser
skif.server_password=test66User

db_hostname=localhost
db_service=DEV1.statkart.no
db_username=SKIF

!! default Datasource
#db_datasource=no.kartverket.skif.storetest.persistence.SkifStoreTest_DS
#db_datasource_old=no.kartverket.skif.storetest.persistence.SkifStoreTestOld_DS

!! Datasource for matrikkelen
db_datasource=no.statkart.matrikkel.persistens.MatrikkelBok_DS
db_datasource_old=no.statkart.matrikkel.persistens.MatrikkelOld_DS

!! Datasource for grunnboken
#db_datasource=no.statkart.grunnbok.gbok.basis.persistens.Grunnbok_DS
#db_datasource_old=no.statkart.grunnbok.gbok.basis.persistens.GrunnbokOld_DS

