service_mode=SINGLE_VM
#service_mode=JEE


skif.server_username=testUser
skif.server_password=test66User

db_hostname=localhost
db_service=DEV1.statkart.no
db_username=SKIF

!! default Datasource
#db_datasource=no.kartverket.skif.storetest.persistence.SkifStoreTest_DS
#db_datasource_old=no.kartverket.skif.storetest.persistence.SkifStoreTestOld_DS

!! Datasource for matrikkelen
db_datasource=no.statkart.matrikkel.persistens.MatrikkelBok_DS
db_datasource_old=no.statkart.matrikkel.persistens.MatrikkelOld_DS

!! Datasource for grunnboken
#db_datasource=grunnbok.Register_DS
#db_datasource_old=grunnbok.RegisterOld_DS

!! Gyldig hostname for bruk med sertifikater (default til %COMPUTERNAME%.statkart.no)
#LOCALHOSTNAME=WSLISLEI1.statkart.no

!! Hvor og hvilken weblogic man har
#WEBLOGIC_HOME=d:/wls_1213
#WEBLOGIC_VERSION=12.1.3
