// Optional configuration of library versions to use.
// Simply add version properties to your gradle.property file to use this feature.
def libVersion(String name, String defaultValue) {
    project.findProperty('version.' + name) ?: defaultValue //development mode only
}

ext.SLF4J_VERSION = libVersion('slf4j', '1.7.25')
// Spesifikasjonen sier bare at JAXB og JAX-WS skal være versjon 2.2.
ext.JAXWS_VERSION = libVersion('jaxws', '2.2.8') // 2.2.10 avhenger av en JAXB-versjon som ikke ser riktig ut.
ext.JAXB_VERSION = libVersion('jaxb', '2.2.7') // Det finnes ingen 2.2.8.
ext.JODATIME_VERSION = libVersion('jodatime', '2.10')
ext.OJDBC8_VERSION = libVersion('oracle', '12.2.0.1')

ext.libraries = [
        // Oracle Weblogic dependencies for deployment
        weblogic   : files(
                "${WEBLOGIC_HOME}/wlserver/server/lib/weblogic.jar",
        ),

        // SKIF-239: Mulighet for valg av ojdbc driver
        jdbc: dependencies.create(ORA_DEBUG ? 'com.oracle.database.jdbc.debug:ojdbc8_g' : 'com.oracle.database.jdbc:ojdbc8') {
            transitive = false
        },
]

allprojects { p ->
    configurations.all { conf ->
        resolutionStrategy {
            failOnVersionConflict()

            dependencySubstitution {
                // Dessverre må man angi versjon man skal erstatte med. Dette må da stemme med skif-internal-platform.
                substitute module('commons-logging:commons-logging') with module("org.slf4j:jcl-over-slf4j:$SLF4J_VERSION")
                substitute module('log4j:log4j') with module("org.slf4j:log4j-over-slf4j:${SLF4J_VERSION}")
            }
        }
    }

    dependencies {
        modules {
            module('com.sun.xml.bind:jaxb-impl') {
                replacedBy('org.glassfish.jaxb:jaxb-runtime', 'New Maven coordinate')
            }
            module('com.sun.xml.bind:jaxb-core') {
                replacedBy('org.glassfish.jaxb:jaxb-runtime', 'New Maven coordinate')
            }
        }
    }
}
