include ':database'

include ':skif-config'
include ':skif-service-common'
include ':skif-testsupport-common'
include ':skif-service-server'
include ':skif-service-test:skif-service-test-api'
include ':skif-service-test:skif-service-test-server'
include ':skif-service-test:skif-service-test-v1-ws:skif-service-test-v1-wsschema'
include ':skif-service-test:skif-service-test-v1-ws:skif-service-test-v1-wsmapping'
include ':skif-service-test:skif-service-test-v1-ws:skif-service-test-v1-wswar'
include ':skif-service-test:skif-service-test-v1-ws:skif-service-test-v1-wsclient'
include ':skif-service-test:skif-service-test-test'
include ':skif-service-test:skif-service-test-ear'

include ':skif-store-common'
include ':skif-store-server'
include ':skif-store-server:skif-store-server-hs36'

include ':skif-store-test:skif-store-test-api'
include ':skif-store-test:skif-store-test-server'
include ':skif-store-test:skif-store-test-test'
include ':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wsschema'
include ':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wsmapping'
include ':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wswar'
include ':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wsclient'
include ':skif-store-test:skif-store-test-ear'

include ':skif-wsversioning:skif-wsversioning-api'
include ':skif-wsversioning:skif-wsversioning-server'
include ':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wscompat'
include ':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wsschema'
include ':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wsmapping'
include ':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wswar'
include ':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wsclient'
include ':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-test'
include ':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wsschema'
include ':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wsmapping'
include ':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wswar'
include ':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wsclient'
include ':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-test'
include ':skif-wsversioning:skif-wsversioning-ear'


rootProject.name = 'skif'

rootProject.children.each { project -> configureProject(project) }
void configureProject(ProjectDescriptor project) {
    project.buildFileName = "${project.name}.gradle"
    assert project.projectDir.isDirectory()

    project.children.each { configureProject(it) }
}


/**
 * Vedlikehold av wrapper via kommando. Feks:
 * gradle wrapper --gradle-version 2.12
 */
gradle.afterProject { project ->
    project.tasks.withType(Wrapper) {
        doFirst {
            // Company wide download service
            distributionUrl = uri("http://devbin.statkart.no:8070/gradle/dists/gradle-${gradleVersion}-all.zip")
            jarFile = gradle.rootProject.file('gradle/wrapper/gradle-wrapper.jar')
            scriptFile = gradle.rootProject.file('gradlew')
        }
    }
}

/*
Until Gradle 4.7, the publishing {} block was implicitly treated as if all the logic inside it was executed after the project is evaluated. This caused quite a bit of confusion, because it was the only block that behaved that way. As part of the stabilization effort in Gradle 4.8, we are deprecating this behavior and asking all users to migrate their build.
The new, stable behavior can be switched on by adding the following to your settings file: enableFeaturePreview('STABLE_PUBLISHING')
*/
if (gradle.gradleVersion >= '4.8') {
    enableFeaturePreview('STABLE_PUBLISHING')
}

/*
Separating compile and runtime scope of modules is active by default in Gradle 5.0+.
In Gradle 4.6+, you need to activate it by adding enableFeaturePreview('IMPROVED_POM_SUPPORT') in settings.gradle.
*/
if (gradle.gradleVersion < '5.0') {
    enableFeaturePreview('IMPROVED_POM_SUPPORT')
}


