pluginManagement {
    def SKTOOLS_VERSION = '7.2026.05.06-07.54-704d771'

    plugins {
        id 'sktools.dbtools' version "$SKTOOLS_VERSION"
        id 'sktools.wsimport' version "$SKTOOLS_VERSION"
        id 'sktools.wsdl-customizer' version "$SKTOOLS_VERSION"
        id 'sktools.wsgen' version "$SKTOOLS_VERSION"
        id 'sktools.xjc' version "$SKTOOLS_VERSION"
    }

    repositories {
        if (Boolean.parseBoolean(System.getenv('MAVEN_LOCAL')) || Boolean.parseBoolean(System.getenv('MAVEN_LOCAL_FOR_BUILDSYSTEM'))) {
            println '...initializing MAVEN_LOCAL_FOR_BUILDSYSTEM'
            mavenLocal()
        }
        maven {
            name = 'GitHubPackages'
            url = 'https://maven.pkg.github.com/kartverket/SkTools'
            credentials {
                username = System.getenv("GITHUB_ACTOR") ?: System.getenv("GITHUB_USER") ?: "token"
                password = System.getenv("PACKAGES_TOKEN") ?: System.getenv("GITHUB_TOKEN")
            }
        }
        mavenCentral()
    }
}

include ':database'

include ':skif-config'
include ':skif-service-common'
include ':skif-testsupport-common'
include ':skif-service-server'
include ':skif-service-test:skif-service-test-api'
include ':skif-service-test:skif-service-test-server'
include ':skif-service-test:skif-service-test-v1-ws:skif-service-test-v1-wsschema'
include ':skif-service-test:skif-service-test-v1-ws:skif-service-test-v1-wsmapping'
include ':skif-service-test:skif-service-test-v1-ws:skif-service-test-v1-wswar'
include ':skif-service-test:skif-service-test-v1-ws:skif-service-test-v1-wsclient'
include ':skif-service-test:skif-service-test-test'
include ':skif-service-test:skif-service-test-ear'

include ':skif-store-common'
include ':skif-store-server'

include ':skif-store-test:skif-store-test-api'
include ':skif-store-test:skif-store-test-server'
include ':skif-store-test:skif-store-test-test'
include ':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wsschema'
include ':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wsmapping'
include ':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wswar'
include ':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wsclient'
include ':skif-store-test:skif-store-test-ear'

include ':skif-wsversioning:skif-wsversioning-api'
include ':skif-wsversioning:skif-wsversioning-server'
include ':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wscompat'
include ':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wsschema'
include ':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wsmapping'
include ':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wswar'
include ':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wsclient'
include ':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-test'
include ':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wsschema'
include ':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wsmapping'
include ':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wswar'
include ':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wsclient'
include ':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-test'
include ':skif-wsversioning:skif-wsversioning-ear'

include ':tomee'


rootProject.name = 'skif'

rootProject.children.each { project -> configureProject(project) }
void configureProject(ProjectDescriptor project) {
    project.buildFileName = "${project.name}.gradle"
    assert project.projectDir.isDirectory()

    project.children.each { configureProject(it) }
}

// Include build for arbeid på tvers av prosjekter
// - konfigureres feks via gradle.properties: includeBuild.wsclient=../matrikkel-wsclient
ext.getProperties().findAll {(it.key as String).startsWith('includeBuild.')}.each {
    println 'Include build ' + file(it.value)
    includeBuild it.value
}
