skif.single_vm=@single_vm@

skif.db_username=@db_username@
skif.db_password=@db_password@
skif.db_hostname=@db_hostname@
skif.db_port=@db_port@
skif.db_sid=@db_sid@
skif.db_datasource=@db_datasource@

skif.db_lock_tablename=@db_lock_tablename@
skif.db_sequence_tablename=@db_sequence_tablename@

skif.testuser_username=enhetstest
skif.testuser_password=matr57stat

