skif.service_mode=@service_mode@

skif.server_username=@skif.server_username@
skif.server_password=@skif.server_password@
skif.server_url=@skif.server_url@
#skif.serverUrl=https://@wls.hostname@:@wls.sport@

skif.testuser_username=@skif.server_username@
skif.testuser_password=@skif.server_password@

