skif.single_vm=@skif.single_vm@

skif.server_username=@skif.server_username@
skif.server_password=@skif.server_password@
skif.server_url=@skif.server_url@
#skif.serverUrl=https://@wls.hostname@:@wls.sport@

skif.db_username=@skif.db_username@
skif.db_password=@skif.db_password@
skif.db_hostname=@skif.db_hostname@
skif.db_port=@skif.db_port@
skif.db_sid=@skif.db_sid@

skif.db_lock_tablename=@skif.db_lock_tablename@

skif.testuser_username=enhetstest
skif.testuser_password=matr57stat

