plugins {
    id 'java-library'
    id 'maven-publish'
    id 'sktools.provided'
}

dependencies {
    api project(':skif-store-common')
    api project(':skif-service-server')
    api libraries.guava //pga Multimap
    api libraries.hibernate

    provided libraries.jee

    implementation libraries.jodatime
    implementation libraries.jdbc //provided
    implementation libraries.hibernate

    compileOnly libraries.openejb_core

    testImplementation project(':skif-config')
    testImplementation project(':skif-testsupport-common')
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            pom.withXml {
                asNode().dependencies.dependency.findAll { 'joda-time' == it.artifactId.text() }.each { it.appendNode('optional', 'true') } //optional avhengighet for joda-time [SKIF-472]
                asNode().dependencies.dependency.findAll { 'com.oracle.database.jdbc' == it.groupId.text() }.each { it.appendNode('optional', 'true'); it.scope[0].value = 'provided'} //optional, provided avhengighet for jdbc drivere - kan brukes for singleVm [SKIF-472]
            }
        }
    }
}
