apply plugin: 'java'
apply plugin: 'maven'

dependencies {
    compile project(':skif-store-common')
    compile project(':skif-service-server')

    compile libraries.jodatime
    compile libraries.jts

    // Sett hibernateVersion i gradle.properties
    // Scope er provided, ein må sjølv inkludere skif-store-server:skif-store-server-hs32 eller skif-store-server:skif-store-server-hs36 i sitt prosjekt
    if(hibernateVersion.equals("3.6")) {
      provided libraries.hibernate_3_6
    }

    compile libraries.gt2

    provided libraries.weblogic

    testCompile project(':skif-config')
    testCompile project(':skif-testsupport-common')
}

task sourcesJar(type: Jar, dependsOn:classes) {
    classifier = 'sources'
    from sourceSets.main.allSource
    onlyIf { gradle.taskGraph.hasTask(install) || gradle.taskGraph.hasTask(uploadArchives) } //only when published..
}

artifacts {
    archives sourcesJar
}


def installer = install.repositories.mavenInstaller
def deployer = uploadArchives.repositories.mavenDeployer

[installer, deployer]*.pom*.whenConfigured { pom ->
    pom.dependencies.findAll { dep -> dep.groupId == 'joda-time' }.each { it.optional = true }  //optional avhengighet for joda-time [SKIF-472]
    pom.dependencies.findAll { dep -> dep.groupId == 'com.vividsolutions' && dep.artifactId == 'jts' }.each { it.optional = true }  //optional avhengighet for jts [SKIF-472]
    pom.dependencies.findAll { dep -> dep.groupId == 'org.geotools' && dep.artifactId == 'gt2-oracle-spatial' }.each { it.optional = true }  //optional avhengighet for gt2 [SKIF-472]
}