apply plugin: 'java-library'
apply plugin: 'maven'

dependencies {
    api project(':skif-store-common')
    api project(':skif-service-server')

    implementation libraries.jodatime

    compileOnly libraries.jdbc

    // Sett hibernateVersion i gradle.properties
    // Scope er provided, ein må sjølv inkludere skif-store-server:skif-store-server-hs32 eller skif-store-server:skif-store-server-hs36 i sitt prosjekt
    if(hibernateVersion == '3.6') {
        compileOnly libraries.hibernate_3_6_api
    }

    compileOnly libraries.weblogic

    testImplementation project(':skif-config')
    testImplementation project(':skif-testsupport-common')
}

task sourcesJar(type: Jar, dependsOn:classes) {
    classifier = 'sources'
    from sourceSets.main.allSource
    onlyIf { gradle.taskGraph.hasTask(install) || gradle.taskGraph.hasTask(uploadArchives) } //only when published..
}

artifacts {
    archives sourcesJar
}


def installer = install.repositories.mavenInstaller
def deployer = uploadArchives.repositories.findByName('mavenDeployer')

[installer, deployer]*.pom*.whenConfigured { pom ->
    pom.dependencies.findAll { dep -> dep.groupId == 'joda-time' }.each { it.optional = true }  //optional avhengighet for joda-time [SKIF-472]
}