plugins {
    id 'java-library'
    id 'sktools.xjc'
}

dependencies {
    // Denne burde egentlig kun legges til classpath som xjc anvender, men vet ikke
    // hvordan man angir dette for sktools.xjc tasken.
    implementation libraries.jaxws_api
    implementation libraries.jaxb_api
}

configurations {
    schemas {
        description = 'Configuration for publishing schemas'
    }
}

sourceSets {
  main {
    xjc {
      schema {
        srcDir 'src/main/schema'
        getWithSkDoc from: 'no.statkart.skif.storetest.wsapi.domain', to: 'no.statkart.skif.teststore.domain'
      }
    }
    resources.srcDirs = []
  }
}


task zipSchemas(type: Zip) {
    archiveClassifier = 'schemas'
    from 'src/main/schema'
}

artifacts {
    schemas zipSchemas
}
