plugins {
    id 'java-library'
    id 'sktools.xjc'
}

dependencies {
    implementation libs.jaxws.api
    implementation libs.jaxb.api

    compileOnly libs.jaxb.runtime
    jaxb libs.jaxb.xjc
}

configurations {
    schemas {
        description = 'Configuration for publishing schemas'
    }
}

sourceSets {
  main {
    xjc {
      schema {
        srcDir 'src/main/schema'
      }
    }
    resources.srcDirs = []
  }
}


task zipSchemas(type: Zip) {
    archiveClassifier = 'schemas'
    from 'src/main/schema'
}

artifacts {
    schemas zipSchemas
}
