apply plugin: 'java'
apply plugin: 'sktools-xjc-plugin'

configurations {
    schemas {
        description = 'Configuration for publishing schemas'
    }
}

sourceSets {
  main {
    xjc {
      schema {
        srcDir 'src/main/schema'
        getWithSkDoc from: 'no.statkart.skif.storetest.wsapi.domain', to: 'no.statkart.skif.teststore.domain'
      }
    }
    resources.srcDirs = []
  }
}

dependencies {
    jaxb libraries.jaxb_xjc
}

//trenger dette for IntelliJ
project.idea.module {
    sourceDirs += sourceSets.main.xjc.collect { file("gen/main/xjc/${it.name}") }
}

task zipSchemas(type: Zip) {
    classifier = 'schemas'
    from 'src/main/schema'
}

artifacts {
    schemas zipSchemas
}
