<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema
        version="1.0"
        targetNamespace="http://skif.statkart.no/storetest/wsapi/domain/basic"
        xmlns:basicns="http://skif.statkart.no/storetest/wsapi/domain/basic"
        xmlns:demoKoderns="http://skif.statkart.no/storetest/wsapi/domain/demo/koder"
        xmlns:domainns="http://skif.statkart.no/storetest/wsapi/domain"
        xmlns:basetyperns="http://skif.statkart.no/storetest/wsapi/domain/basetyper"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified">

    <xs:import schemaLocation="demoKoder.xsd" namespace="http://skif.statkart.no/storetest/wsapi/domain/demo/koder"/>
    <xs:import schemaLocation="domain.xsd" namespace="http://skif.statkart.no/storetest/wsapi/domain"/>
    <xs:import schemaLocation="basetyper.xsd" namespace="http://skif.statkart.no/storetest/wsapi/domain/basetyper"/>

    <!-- ================================================= -->
    <!-- Basisklasser                                      -->
    <!-- ================================================= -->

    <xs:complexType name="SimpleId">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubbleId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="SimpleIdList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="basicns:SimpleId"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Simple">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubble">
                <xs:sequence>
                    <xs:element name="nr" type="xs:int" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="text" type="xs:string" minOccurs="1" maxOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="BubbleWithFilterId">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubbleId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="BubbleWithFilterIdList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="basicns:BubbleWithFilterId"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="BubbleWithFilter">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubble">
                <xs:sequence>
                    <xs:element name="nr" type="xs:int" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="text" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="filter" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="filterText" type="xs:string" minOccurs="1" maxOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="BubbleWithKodeId">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubbleId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="BubbleWithKodeIdList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="basicns:BubbleWithKodeId"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="BubbleWithKode">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubble">
                <xs:sequence>
                    <xs:element name="nr" type="xs:int" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="text" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="testAEnumKodeId" type="demoKoderns:TestAEnumKodeId" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="testC2DbKodeId" type="demoKoderns:TestC2DbKodeId" minOccurs="1" maxOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="BubbleWithRelationId">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubbleId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="BubbleWithRelationIdList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="basicns:BubbleWithRelationId"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="BubbleWithRelation">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubble">
                <xs:sequence>
                    <xs:element name="nr" type="xs:int" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="text" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="simpleId" type="basicns:SimpleId" minOccurs="1" maxOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="HistSimpleId">
        <xs:complexContent>
            <xs:extension base="domainns:AbstractStoreTestBubbleWithHistoryId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="HistSimpleIdList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="basicns:HistSimpleId"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="HistSimple">
        <xs:complexContent>
            <xs:extension base="domainns:AbstractStoreTestBubbleWithHistory">
                <xs:sequence>
                    <xs:element name="nr" type="xs:int" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="text" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="testSetNumber" type="xs:int" minOccurs="1" maxOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="HistWithRelationId">
        <xs:complexContent>
            <xs:extension base="domainns:AbstractStoreTestBubbleWithHistoryId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="HistWithRelationIdList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="basicns:HistWithRelationId"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="HistWithRelation">
        <xs:complexContent>
            <xs:extension base="domainns:AbstractStoreTestBubbleWithHistory">
                <xs:sequence>
                    <xs:element name="nr" type="xs:int" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="text" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="testSetNumber" type="xs:int" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="histSimpleId" type="basicns:HistSimpleId" minOccurs="1" maxOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="GeometricElementId">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubbleId"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="GeometricElementIdList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="basicns:GeometricElementId"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="GeometricElement">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubble"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="SubTypedBubbleId">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubbleId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="SubTypedBubble">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubble">
                <xs:sequence>
                    <xs:element name="text" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!--<xs:complexType name="Endringsklasse">-->
        <!--<xs:sequence>-->
            <!--<xs:element name="value" type="xs:string"/>-->
        <!--</xs:sequence>-->
    <!--</xs:complexType>-->
    <xs:simpleType name="Endringsklasse">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Endring" />
            <xs:enumeration value="SimpleEndring" />
            <xs:enumeration value="SubTypedBubbleEndring" />
            <xs:enumeration value="X1AAEndring" />
            <xs:enumeration value="X1BBOneEndring" />
            <xs:enumeration value="X1CCManyEndring" />
        </xs:restriction>
    </xs:simpleType>


    <xs:complexType name="EndringId">
        <xs:sequence>
            <xs:element name="value" type="xs:string"/>
            <xs:element name="snapshotVersion" type="domainns:SnapshotVersion"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Endring">
        <xs:sequence>
            <xs:element name="id" type="basicns:EndringId"/>
            <xs:element name="versjonId" type="xs:long"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="EndringList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="basicns:Endring"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="BubbleWithRelationEndring">
        <xs:complexContent>
            <xs:extension base="basicns:Endring">
                <xs:sequence>
                    <xs:element name="bubbleWithRelationId" type="basicns:BubbleWithRelationId" minOccurs="1" maxOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>

    </xs:complexType>

    <xs:complexType name="SimpleEndring">
        <xs:complexContent>
            <xs:extension base="basicns:Endring">
                <xs:sequence>
                    <xs:element name="simpleId" type="basicns:SimpleId" minOccurs="1" maxOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>

    </xs:complexType>

    <xs:complexType name="SubTypedBubbleEndring">
        <xs:complexContent>
            <xs:extension base="basicns:Endring">
                <xs:sequence>
                    <xs:element name="subTypedId" type="basicns:SubTypedBubbleId" minOccurs="1" maxOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="Domeneklasse">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Simple" />
            <xs:enumeration value="SubTypedBubble" />
            <xs:enumeration value="X1AA" />
            <xs:enumeration value="X1BBOne" />
            <xs:enumeration value="X1CCMany" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Kontroll">
        <xs:sequence>
            <xs:element name="antall" type="xs:long"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SubTypeWithPrimitiveId">
        <xs:complexContent>
            <xs:extension base="basicns:SubTypedBubbleId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="SubTypeWithPrimitive">
        <xs:complexContent>
            <xs:extension base="basicns:SubTypedBubble">
                <xs:sequence>
                    <xs:element name="num" type="xs:int"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="SubTypeWithCollectionId">
        <xs:complexContent>
            <xs:extension base="basicns:SubTypedBubbleId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <xs:complexType name="SubTypeWithCollection">
        <xs:complexContent>
            <xs:extension base="basicns:SubTypedBubble">
                <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="tekster" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>



    <xs:complexType name="X1AAId">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubbleId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="X1AA">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubble">
                <xs:sequence>
                    <xs:element name="someBBId" type="basicns:X1BBOneId" minOccurs="1" maxOccurs="1"/>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="someCCsIds" type="basicns:X1CCManyId"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <xs:complexType name="X1AAIdSet">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="basicns:X1AAId"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="X1AAIdSetForX1BBOneIdMap">
          <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="entry">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="key" nillable="true" type="basicns:X1BBOneId"/>
                        <xs:element name="value" type="basicns:X1AAIdSet"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="X1AAIdForX1CCManyIdMap">
          <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="entry">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="key" nillable="true" type="basicns:X1CCManyId"/>
                        <xs:element name="value" type="basicns:X1AAId"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="X1BBOneId">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubbleId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="X1BBOne">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubble">

            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="X1BBOneIdCollection">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="basicns:X1BBOneId"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="X1CCManyId">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubbleId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="X1CCMany">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubble">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="X1CCManyIdCollection">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="basicns:X1CCManyId"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>
