<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema
        version="1.0"
        targetNamespace="http://skif.statkart.no/storetest/wsapi/domain/kodeliste"
        xmlns:kodelistens="http://skif.statkart.no/storetest/wsapi/domain/kodeliste"
        xmlns:domainns="http://skif.statkart.no/storetest/wsapi/domain"
        xmlns:basetyperns="http://skif.statkart.no/storetest/wsapi/domain/basetyper"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified">

    <xs:import schemaLocation="domain.xsd" namespace="http://skif.statkart.no/storetest/wsapi/domain"/>
    <xs:import schemaLocation="basetyper.xsd" namespace="http://skif.statkart.no/storetest/wsapi/domain/basetyper"/>

    <xs:complexType name="KodeId">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubbleId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="KodeIdList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="kodelistens:KodeId"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="KodeIdTestList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Kode">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubble">
                <xs:sequence>
                    <xs:element name="kodelisteId" type="kodelistens:KodelisteId"/>
                    <xs:element name="kodeverdi" type="xs:string"/>
                    <xs:element name="beskrivelse" type="basetyperns:LocalizedString"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="KodeList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="kodelistens:Kode"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="KodelisteId">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubbleId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="KodelisteStringId">
        <xs:complexContent>
            <xs:extension base="kodelistens:KodelisteId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="KodelisteLongId">
        <xs:complexContent>
            <xs:extension base="kodelistens:KodelisteId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="KodelisteIdList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="kodelistens:KodelisteId"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Kodeliste">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubble">
                <xs:sequence>
                    <xs:element name="kodeIdClass" type="xs:string"/>
                    <xs:element name="navn" type="basetyperns:LocalizedString"/>
                    <xs:element name="beskrivelse" type="basetyperns:LocalizedString"/>
                    <xs:element name="koderIds" type="kodelistens:KodeIdList"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="KodelisteString">
        <xs:complexContent>
            <xs:extension base="kodelistens:Kodeliste">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="KodelisteLong">
        <xs:complexContent>
            <xs:extension base="kodelistens:Kodeliste">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="KodelisteList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="kodelistens:Kodeliste"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="KodelisteTransfer">
        <xs:sequence>
            <xs:element name="result" type="kodelistens:KodelisteIdList"/>
            <xs:element name="bubbleObjects" type="domainns:StoreTestBubbleList"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>
