plugins {
    id 'java-base' // For at platform skal virke, selv transitivt.
    id 'ear'
    id 'sktools.weblogic-deploy'
}

def warMap = [
        ':skif-service-test:skif-service-test-v1-ws:skif-service-test-v1-wswar': 'skiftest/wsapi',
]

def ejbList = [
        ':skif-service-test:skif-service-test-server'
]

dependencies {
    ejbList.each {
        def p = project(it)
        deploy p
        earlib p
    }
    warMap.each {
        deploy project(path: it.key, configuration: 'war')
        earlib project(path: it.key, configuration: 'earlib')
    }

    // TODO: Bør noen av de andre modulene trekke med seg denne (de har den nå på testCompile)?
    earlib project(':skif-config')
}

libDirName = 'APP-INF/lib'
deploymentDescriptor {
    version = '5'
    displayName = 'skif-service-test'
    warMap.each {
        def p = project(it.key)
        webModule(p.name + '-' + p.version + '.war', it.value)
    }
}

weblogicDeploy {
    classpath = libraries.weblogic
    url(host: wls_deploy_hostname, port: wls_deploy_port, protocol: wls_deploy_protocol)
    targets = wls_deploy_targets
    username = wls_username
    password = wls_password

    file = ear
    name = archivesBaseName

    undeployTask('undeploy', description: "Undeployer ${name} til ${url}")

    deployTask('deploy', dependsOn: [undeployTask], description: "Deployer ${name} til ${url}") {
        deployerTimeout = 1200000
    }
}
