apply plugin: 'ear'
apply plugin: 'sktools-weblogic-deploy-plugin'

Map warMap = [
        ':skif-service-test:skif-service-test-wswar': 'skiftest/wsapi',
]

List ejbList = [
        ':skif-service-test:skif-service-test-server'
]

dependencies {
    ejbList.each {
        def p = project(it)
        deploy p
        earlib p
    }
    warMap.each {
        def p = project(path: it.key, configuration: 'weblogic')
        deploy p
        earlib p
    }

    // TODO: Bør noen av de andre modulene trekke med seg denne (de har den nå på testCompile)?
    earlib project(':skif-config')
}

ear {
    libDirName 'APP-INF/lib'
    deploymentDescriptor {
        version = "5"
        displayName = "skif-service-test"
        warMap.each {
            def p = project(it.key)
            webModule(p.name + '-weblogic-' + p.version + ".war", it.value)
        }
    }
}

weblogicDeploy {
    classpath = libraries.weblogic
    url(host: wls_deploy_hostname, port: wls_deploy_port, protocol: wls_deploy_protocol)
    targets = wls_deploy_targets
    username = wls_username
    password = wls_password

    file = ear
    name = archivesBaseName

    undeployTask('undeploy', description: "Undeployer ${name} til ${url}")

    deployTask('deploy', dependsOn: [undeployTask], description: "Deployer ${name} til ${url}") {
        timeout = 1200000
    }
}
