plugins {
  id 'java'
  id 'sktools.xjc'
}

dependencies {
  implementation libraries.jaxws_api
  implementation libraries.jaxb_api

  compileOnly libraries.jaxb_runtime
  jaxb libraries.jaxb_xjc
}

sourceSets {
  main {
    xjc {
      schema {
        srcDir 'src/main/schema'
      }
    }
    resources.srcDirs = []
  }
}
