apply plugin: 'java'
apply plugin: 'sktools-xjc-plugin'

sourceSets {
  main {
    xjc {
      schema {
        srcDir 'src/main/schema'
        getWithSkDoc from: 'no.statkart.skif.wsversioning.wsapi.v1.domain', to: 'no.statkart.skif.wsversioning.domain'
      }
    }
    resources.srcDirs = []
  }
}

dependencies {
    jaxb libraries.jaxb_xjc
}
