plugins {
    id 'java-library'
    id 'sktools.xjc'
}

sourceSets {
    main {
        xjc {
            schema {
                srcDir 'src/main/schema'
                getWithSkDoc from: 'no.statkart.skif.wsversioning.wsapi.v1.domain', to: 'no.statkart.skif.wsversioning.domain'
            }
        }
        resources.srcDirs = []
    }
}
