plugins {
    id 'sktools.wsgen'
}

configurations {
    war { description = 'War-artifaktet' }
    wsdls { description = 'Zip med WSDL-er' }
    earlib { extendsFrom implementation; description = 'Felles avhengheter i ear (skinny wars)'}
}

dependencies {
    implementation project(':skif-wsversioning:skif-wsversioning-server')
    implementation project(':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wsschema')
    implementation project(':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wsmapping')

    compileOnly libraries.jee
    compileOnly libraries.jaxws_api

    jaxws libraries.jaxws_tools
}

war {
    // Skinny war
    classpath = sourceSets.main.output
}

task zipWsdls(type: Zip) {
    archiveClassifier = 'wsdls'
    from genWsdls
}

artifacts {
    wsdls zipWsdls
    war project.war
}
