apply plugin: 'sktools-wsgen-plugin'

configurations {
    war { description = 'War-artifaktet' }
    wsdls { description = 'Zip med WSDL-er' }
}

dependencies {
    compile project(':skif-wsversioning:skif-wsversioning-server')
    compile project(':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wsschema')
    compile project(':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wsmapping')

    provided libraries.jee

    jaxws project(':skif-config') // For å tvinge bruk av JAX-WS RI og JAXB RI
    jaxws libraries['tools.jar']
    jaxws libraries.weblogic
}

war {
    // Skinny war
    classpath = sourceSets.main.output
}

task zipWsdls(type: Zip) {
    classifier = 'wsdls'
    extension = 'war'
    from genWsdls
}

artifacts {
    wsdls zipWsdls
    war project.war
}
