plugins {
    id 'java-library'
    id 'maven-publish'
}

description = 'Inneholder service-rammeverk klasser for klient'

configurations {
    testApi
}

dependencies {
    api libs.slf4j.api
    api libs.guice
    api libs.guava //pga TypeToken

    implementation libs.guava
    implementation libs.jodatime
    implementation libs.commons.pool
    compileOnly libs.jaxws.api
    compileOnly libs.bundles.jee

    testImplementation libs.bundles.jaxws.rt
    testImplementation libs.reflections
    testImplementation libs.logback.classic
}

task testJar(type: Jar) {
    archiveClassifier = 'tests'
    from sourceSets.test.output
}

artifacts {
    testApi testJar
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            pom.withXml {
                asNode().dependencies.dependency.findAll { 'joda-time' == it.artifactId.text() }.each { it.appendNode('optional', 'true') } //optional avhengighet for joda-time [SKIF-472]
            }
        }
    }
}

def assertDependencies = tasks.register("assertDependencies") {
    doFirst {
        configurations.apiElements.getAllDependencies().each { Dependency dependency ->
            if (dependency instanceof SelfResolvingDependency) return
            boolean godkjent = [
                'org.slf4j',
                'com.google.inject:guice',
                'com.google.guava:guava',
            ].find { "${dependency.group}:${dependency.name}:${dependency.version}".startsWith(it) }

            if (!godkjent) {
                throw new TaskExecutionException(it, new RuntimeException('Ukjent avhengighet: ' + dependency))
            }
        }
    }
}
test.dependsOn assertDependencies //kjøres som en test
