plugins {
    id 'java-library'
    id 'maven-publish'
}

description = 'Inneholder service-rammeverk klasser for klient'

java {
    registerFeature('jodatimeSupport') {
        usingSourceSet(sourceSets.main)
    }

    // TODO: Skill det testene bruker fra selve testene
    registerFeature('test') {
        usingSourceSet(sourceSets.test)
    }

    withSourcesJar()
}

dependencies {
    api enforcedPlatform(project(':skif-service-platform'))

    api 'org.slf4j:slf4j-api'
    api 'com.google.inject:guice'
    api 'com.google.guava:guava' //pga TypeToken

    compileOnlyApi 'javax.xml.ws:jaxws-api'

    compileOnly 'com.google.code.findbugs:jsr305'


    jodatimeSupportApi enforcedPlatform(project(':skif-service-platform'))

    jodatimeSupportApi 'joda-time:joda-time'


    testApi enforcedPlatform(project(':skif-internal-platform'))

    testImplementation 'org.reflections:reflections'
    testImplementation 'org.assertj:assertj-core'
}

components.java {
    // Disse skal bare brukes internt
    withVariantsFromConfiguration(configurations.testApiElements) {
        skip()
    }
    withVariantsFromConfiguration(configurations.testRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            suppressPomMetadataWarningsFor('jodatimeSupportApiElements')
            suppressPomMetadataWarningsFor('jodatimeSupportRuntimeElements')
        }
    }
}

task assertDependencies() {
    doFirst {
        configurations.runtimeElements.copyRecursive{it instanceof ExternalDependency}.dependencies.each { Dependency dependency ->
            boolean godkjent = [
                    'joda-time',
                    'org.slf4j',
                    'com.google.code.findbugs:jsr305',
                    'com.google.inject:guice',
                    'com.google.guava:guava',
            ].find { "${dependency.group}:${dependency.name}:${dependency.version}".startsWith(it) }

            if (!godkjent) {
                throw new TaskExecutionException(it, new RuntimeException('Ukjent avhengighet: ' + dependency)) //avhengighet ikke i godkjent-liste
            }
        }
    }
}
check.dependsOn assertDependencies
