apply plugin: 'java'
apply plugin: 'maven'

configurations {
    testApi
}

dependencies {
    compile libraries.slf4j_api
    compile libraries.jsr305
    compile libraries.guice_for_client
    compile libraries.guava
    compile libraries.jodatime
    provided libraries.jaxws_rt

    testCompile libraries.reflections
}

println sourceSets.main.compileClasspath.asPath

task testJar(type: Jar) {
    classifier = 'tests'
    from sourceSets.test.output
}


task javadocJar(type: Jar, dependsOn:javadoc) {
    classifier = 'javadoc'
    from javadoc.destinationDir
    onlyIf { gradle.taskGraph.hasTask(install) || gradle.taskGraph.hasTask(uploadArchives) } //only when published..
}

task sourcesJar(type: Jar, dependsOn:classes) {
    classifier = 'sources'
    from sourceSets.main.allSource
    onlyIf { gradle.taskGraph.hasTask(install) || gradle.taskGraph.hasTask(uploadArchives) } //only when published..
}

artifacts {
    testApi testJar
    archives sourcesJar
    archives javadocJar
}

task assertDependencies() {
    //kjøres som en test
    test.dependsOn it

    doFirst {
        configurations.runtime.copyRecursive{it instanceof ExternalDependency}.dependencies.each { Dependency dependency ->
            boolean godkjent = [
                    'joda-time',
                    'org.slf4j',
                    'com.google.code.findbugs:jsr305',
                    'com.google.inject:guice',
                    'com.google.guava:guava',
                    'com.google.inject.extensions:guice-',
            ].find { "${dependency.group}:${dependency.name}:${dependency.version}".startsWith(it) }

            if (!godkjent) {
                throw new TaskExecutionException(it, new RuntimeException('Ukjent avhengighet: ' + dependency)); //avhengighet ikke i godkjent-liste
            }
        }
    }
}
