plugins {
    id 'java-platform'
}

javaPlatform {
    // Kun for å arve andre platformer!
    allowDependencies()
}

dependencies {
    constraints {
        // Logging
        runtime "org.slf4j:jcl-over-slf4j:${SLF4J_VERSION}"
        runtime "org.slf4j:jul-to-slf4j:${SLF4J_VERSION}"
        runtime "org.slf4j:log4j-over-slf4j:${SLF4J_VERSION}"
        api 'ch.qos.logback:logback-classic:1.2.3' // skif-store-test-test bruker logback direkte

        // Database
        api "com.oracle.database.jdbc:ojdbc8:${OJDBC8_VERSION}"
        api "com.oracle.database.jdbc.debug:ojdbc8_g:${OJDBC8_VERSION}"
        api 'com.mchange:c3p0:0.9.5.2'

        api "com.sun.xml.bind:jaxb-core:${JAXB_VERSION}"
        api "com.sun.xml.ws:jaxws-rt:${JAXWS_VERSION}"
        api 'org.jvnet.mimepull:mimepull:1.9.1' // jaxws-rt trekker inn 1.9 direkte og 1.9.1 indirekte

        api "com.google.code.findbugs:jsr305:1.3.9"

        // Testing
        api 'org.testng:testng:6.14.3'
        api 'org.mockito:mockito-core:2.19.0' /* mockito 3.x for java 8 */
        api 'net.bytebuddy:byte-buddy:1.8.17' // mockito vil ha 1.8.10, hibernate 1.8.17. Lar siste vinne.
        api 'org.dbunit:dbunit:2.5.4'
        api 'org.unitils:unitils-core:3.4.6'
        api 'org.assertj:assertj-core:3.17.0'
        api 'org.reflections:reflections:0.9.11'
        api 'com.thoughtworks.xstream:xstream:1.4.8'
    }

}
