apply plugin: 'maven'

dependencies {
    compile project(':skif-store-server')
    compile libraries.hibernate_3_2

    provided libraries.weblogic

    testCompile project(':skif-config')
    testCompile project(':skif-testsupport-common')

}

task sourcesJar(type: Jar, dependsOn:classes) {
    classifier = 'sources'
    from sourceSets.main.allSource
    onlyIf { gradle.taskGraph.hasTask(install) || gradle.taskGraph.hasTask(uploadArchives) } //only when published..
}
