plugins {
    id 'java'
}

dependencies {
    testImplementation project(':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wsmapping')
    testImplementation project(':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wsclient')
    testImplementation project(':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wswar')
    testImplementation project(':skif-wsversioning:skif-wsversioning-server')

    testImplementation project(':skif-testsupport-common')
    testRuntimeOnly project(':skif-config')

    testRuntimeOnly 'javax.ejb:ejb-api'
}
