plugins {
    id 'java'
    id 'sktools.provided'
}

dependencies {
    implementation project(':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wsmapping')
    implementation project(':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wsclient')

    provided project(':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wswar')

    provided libraries.jee

    testImplementation project(':skif-wsversioning:skif-wsversioning-server')
    testImplementation project(':skif-testsupport-common')
    testRuntimeOnly project(':skif-config')
}
