apply plugin: 'java'

dependencies {
    compile project(':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wsmapping')
    compile project(':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wsclient')

    provided project(':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wswar')

    provided libraries.jee

    testCompile project(':skif-testsupport-common')
    testRuntime project(':skif-config')
}
