apply plugin: 'statkart-xjc-plugin'

dependencies {
    jaxb libraries.jaxb_xjc
    jaxb libraries.build_utils
}

statKartXjc {
    String jaxbSourceDir = 'src/main/schema'
    schema(jaxbSourceDir, '**/*.xsd', 'no.statkart.skif.storetest.wsapi.domain no.statkart.skif.teststore.domain')
    xjcLibraries = configurations.jaxb
}
