apply plugin: 'java-library'
apply plugin: 'maven-publish'

dependencies {
    api project(':skif-store-server')
    api libraries.hibernate_3_6_api
    api libraries.guava //pga Multimap

    implementation libraries.hibernate_3_6

    implementation libraries.jta //optional
    compileOnly libraries.weblogic

    testImplementation project(':skif-config')
    testImplementation project(':skif-testsupport-common')
}

task sourcesJar(type: Jar, dependsOn:classes) {
    classifier = 'sources'
    from sourceSets.main.allSource
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact sourcesJar

            pom.withXml {
                asNode().dependencies.dependency.findAll { 'javax.transaction' == it.groupId.text() && 'jta' == it.artifactId.text() }.each { it.appendNode('optional', 'true') } //optional avhengighet for javax.transaction:jta [SKIF-678]
            }
        }
    }
}
