plugins {
    id 'java-library'
    id 'maven-publish'
    id 'sktools.provided'
}

dependencies {
    api project(':skif-store-server')
    api libraries.hibernate_3_6_api
    api libraries.guava //pga Multimap

    provided libraries.jee

    implementation libraries.hibernate_3_6

    testImplementation project(':skif-config')
    testImplementation project(':skif-testsupport-common')
}

task sourcesJar(type: Jar, dependsOn:classes) {
    archiveClassifier = 'sources'
    from sourceSets.main.allSource
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact sourcesJar
        }
    }
}
