apply plugin: 'java'
apply plugin: 'sktools-xjc-plugin'


sourceSets {
  main {
    xjc {
      schema {
        srcDir 'src/main/schema'
        getWithSkDoc from: 'no.statkart.skif.skiftest.wsapi.domain', to: 'no.statkart.skif.skiftest.domain'
      }
    }
    resources.srcDirs = []
  }
}

dependencies {
    jaxb libraries.jaxb_xjc
}
