plugins {
    id 'java-library'
    id 'maven-publish'
}

dependencies {
    api project(':skif-service-common')
    api (libs.testing){
        exclude group:'junit' // vi benytter ikke JUnit i prosjektet [SKIF-385]
    }
    compileOnly libs.jaxws.api
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
