apply plugin: 'java'
apply plugin: 'maven'

dependencies {
    compile project(':skif-service-common')
    compile libraries.testng
}

task sourcesJar(type: Jar, dependsOn:classes) {
    classifier = 'sources'
    from sourceSets.main.allSource
    onlyIf { gradle.taskGraph.hasTask(install) || gradle.taskGraph.hasTask(uploadArchives) } //only when published..
}

artifacts {
    archives sourcesJar
}