configurations {
    client
}

dependencies {
    //tester disse implementasjonene her..
    if (hibernateVersion.equals("3.2")) {
        compile project(':skif-store-server:skif-store-server-hs32')

        // SchemaGen trenger disse
        runtime libraries.jcl_to_slf4j
        runtime 'commons-collections:commons-collections:2.1.1'
    } else if (hibernateVersion.equals("3.6")) {
        compile project(':skif-store-server:skif-store-server-hs36')
    }

    compile project(':skif-store-test2:skif-store-test2-api')

    provided libraries.weblogic

    testCompile project(':skif-testsupport-common')

    //internal dependencies + optional deps to logging frameworks:
    testCompile project(':skif-config')
}


ideaModule {
    doFirst {
        //SKIF-239: legger inn vanlig driver + debugdriver inn i IntelliJ prosjektet for enkel manuell switching av rekkefølge på classpath.
        project.dependencies {
            provided libraries.ojdbc
            provided libraries.ojdbc_g
        }
    }
}


task generateSchemaFromHibernate(type: JavaExec, dependsOn: configurations.runtime) {
    description = "Lager skjema og plasserer det modulroten"

    def outputFile = file('db_schema.ddl')

//    outputs.file outputFile

    doFirst {
        println "Genererer databaseskjema til filen: ${outputFile}"

        // sourceSets.main.output.filterResourcesOutputDir er ikke evaluert før doFirst
        args = [
                "--output=${outputFile}",
                "--delimiter=;",
                "--format",
                "--text",
                "--quiet",
                "--create",
        ]

        args += getAllHbmXmlPaths(project.file('src/main/resources/no/statkart/skif/storetest2/persistence/hibernate'))
    }

    main = 'org.hibernate.tool.hbm2ddl.SchemaExport'
    classpath = sourceSets.main.runtimeClasspath

    systemProperties = [
            'hibernate.dialect': 'org.hibernate.dialect.Oracle10gDialect',
    ]
}

private List getAllHbmXmlPaths(def packageDir) {
    // Denne må komme først, noe den ikke gjør som del av samme filetree som resten
    FileTree enumHbm = fileTree(packageDir) {
        include('type/EnumKodeIdType.hbm.xml')
    }

    FileTree hbms = fileTree(packageDir) {
        include('*.hbm.xml')
    }

    List filenames = []

    enumHbm.files.each { File f ->
        filenames += f.absolutePath
    }
    hbms.files.each { File f ->
        filenames += f.absolutePath
    }

    filenames
}