apply plugin: 'statkart-wsclient-plugin'
apply plugin: 'statkart-javadoc-plugin'

dependencies {
    basewar project(':skif-store-test:skif-store-test-wswar')
}

wsClient {
    weblogicLibraries = configurations.weblogic

    fixExceptionsFor = [[
            exceptionPackageImport: 'import no.statkart.skif.storetest.wsapi.exception.*;',
            exceptionPackage: 'no/statkart/skif/storetest/wsapi/exception',
            exceptionFilePattern: '**/wsapi/service/**/*Exception.java',
            regexpMatch: /package no\.statkart\.skif\.storetest\.wsapi\.service(\..+)*;/,
            regexpReplace: /package no\.statkart\.skif\.storetest\.wsapi\.exception;/
    ]]
}
