apply plugin: 'java'
apply plugin: 'sktools-wsimport-plugin'

configurations {
    wsdls
}

dependencies {
    wsdls project(path: ':skif-service-test:skif-service-test-v1-ws:skif-service-test-v1-wswar', configuration: 'wsdls')

    implementation libraries.jaxws_rt

    jaxws libraries.jaxws_tools
}

// https://discuss.gradle.org/t/right-way-to-copy-contents-from-dependency-archives/7449/13
task importWsdls(type: Sync) {
    dependsOn configurations.wsdls

    into('META-INF/wsdls/skif-service') {
        from { configurations.wsdls.collect { zipTree(it) } }
    }

    into "$buildDir/wsdls/"
}

processResources.dependsOn importWsdls
sourceSets.main.resources.srcDir importWsdls.destinationDir

wsimport {
    exceptionReusePackage 'no.statkart.skif.skiftest.wsapi.exception'
}
