plugins {
    id 'java-library'
    id 'sktools.wsimport'
}

configurations {
    wsdls
}

dependencies {
    runtimeOnly enforcedPlatform(project(':skif-internal-platform'))

    wsdls project(path: ':skif-service-test:skif-service-test-v1-ws:skif-service-test-v1-wswar', configuration: 'wsdls')

    runtimeOnly 'com.sun.xml.ws:jaxws-rt'
}

// https://discuss.gradle.org/t/right-way-to-copy-contents-from-dependency-archives/7449/13
task importWsdls(type: Sync) {
    dependsOn configurations.wsdls

    into('META-INF/wsdls/skif-service') {
        from { configurations.wsdls.collect { zipTree(it) } }
    }

    into "$buildDir/wsdls/"
}

processResources.dependsOn importWsdls
sourceSets.main.resources.srcDir importWsdls.destinationDir

wsimport {
    exceptionReusePackage 'no.statkart.skif.skiftest.wsapi.exception'
}
