import no.statkart.gradle.util.DependencyUtil

apply plugin: 'statkart-weblogic-wswar-plugin'

dependencies {
    compile project(':skif-store-test:skif-store-test-server')
    compile project(':skif-store-test:skif-store-test-wsmapping')

    provided libraries.weblogic
    provided files(DependencyUtil.getJavaTools())
}

statKartWeblogicWsWar {
    sourceDir = 'src/main/java'
    classpath = configurations.compile + configurations.provided
    weblogicLibraries = configurations.weblogic
}
