-- Script for manuell opprettelse av sikkerhetsskjema for SKIF basert på dokumentasjon fra SKIF-394.

ALTER SESSION SET CURRENT_SCHEMA = "SKIF_USERS";

CREATE TABLE "USERS" (
U_NAME VARCHAR(64) not null,
U_PASSWORD VARCHAR(256) not null,
U_DESCRIPTION VARCHAR(256),
PRIMARY KEY (U_NAME))
;

CREATE TABLE "GROUPS" (
G_NAME VARCHAR(64),
G_DESCRIPTION VARCHAR(256),
PRIMARY KEY (G_NAME))
;

CREATE TABLE "GROUPMEMBERS" (
G_NAME VARCHAR(64),
G_MEMBER VARCHAR(64))
;

create index GROUPMEMBERS_NAME on "GROUPMEMBERS" (G_NAME);
create index GROUPMEMBERS_MEMBER on "GROUPMEMBERS" (G_MEMBER);
alter table "GROUPMEMBERS" add constraint GROUPMEMBERS_NAME_FK foreign key (G_NAME) references "GROUPS" ;
