-- Script for manuell opprettelse av sikkerhetsdatabasebruker for SKIF basert på dokumentasjon fra SKIF-394.
-- Dette script må kjøres som systembruker for databasen
-- NB: Lokasjon for DATAFILE må tilpasse til databasen som anvendes

CREATE TABLESPACE "SKIF_USERS"
DATAFILE 'C:\oracle\Oradata\DEV1\SKIF_USERS_01.DBF' SIZE 1M
LOGGING
EXTENT MANAGEMENT LOCAL SEGMENT
SPACE MANAGEMENT AUTO
;

CREATE USER "SKIF_USERS"
IDENTIFIED BY "SKIF_USERS"
DEFAULT TABLESPACE "SKIF_USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK
;

ALTER USER "SKIF_USERS" QUOTA UNLIMITED ON "SKIF_USERS";
GRANT CREATE SESSION TO "SKIF_USERS";
GRANT ALTER SESSION TO "SKIF_USERS";
GRANT CREATE TABLE TO "SKIF_USERS";
SELECT * FROM SYS.DBA_SYS_PRIVS WHERE GRANTEE = 'SKIF_USERS'
;