apply plugin: 'sktools-dbtools-plugin'



// properties for substituering
def filterProperties  = [
        db_username: db_username,
        db_schema: db_username,
]

configureDatabasePlugin {
    useDrivers libraries.ojdbc

    project.ext.tns = "${db_sid}_${db_hostname}"

    toolset(name: '', type: 'oracle', prefix: '') {
        sqlTask('purge', sqlFile: 'src/main/sql/oracle/schema/Purge.sql')
        sqlTask('createSchema', sqlFile: 'src/main/sql/oracle/schema/CreateSchema.sql')
        sqlTask('loadTestdata', sqlFile: 'src/main/sql/oracle/data/LoadTestdata.sql')

        properties = project.properties

        credentials.username = db_username
        credentials.password = db_username
        url = "jdbc:oracle:thin:@${db_hostname}:${db_port}:${db_sid}"
    }

    /**
     * Toolset for SYSTEM-bruker
     */
    toolset(name: 'sa', type: 'oracle', prefix: 'sa') {
        sqlTask('grant', sqlFile: 'src/main/sql/oracle/schema/GrantRole.sql')

        properties = filterProperties

        credentials.username = admin_db_username
        credentials.password = admin_db_password
        url = "jdbc:oracle:thin:@${db_hostname}:${db_port}:${db_sid}"

    }

}


task dbInit {
    description = 'Purger schema, oppretter schema og fyller inn testdata'

    int i = 0 //hacker til nytt lag av tasker da gradle 1.0 eksekverer dependencies i alfabetisk rekkefølge
    dependsOn project.task(String.format('%s_step%02d', it.name, ++i), dependsOn: dbToolSets[''].tasks['purge'])
    dependsOn project.task(String.format('%s_step%02d', it.name, ++i), dependsOn: dbToolSets[''].tasks['createSchema'])
    dependsOn project.task(String.format('%s_step%02d', it.name, ++i), dependsOn: dbToolSets[''].tasks['loadTestdata'])

}