apply plugin: 'sktools-dbtools-plugin'


configurations {
    drivers
}

dependencies {
    drivers libraries.ojdbc
}



configureDatabasePlugin {

    //todo: endre navn til db_hostname i plugin?
    if (hasProperty('db_host')) {
        setProperty 'db_hostname', properties['db_host']
    }

    useDrivers configurations.drivers

    useToolset('oracle', '', 'main/sql/oracle') {
        url = "jdbc:oracle:thin:@${project.property('db_hostname')}:${project.property('db_port')}:${project.property('db_sid')}"
    }

}

task dbInit {

    description = 'Purger schema, oppretter schema og fyller inn testdata'
    def tasks = [tasks.Purge, tasks.CreateSchema, tasks.LoadTestdata]

    tasks.each {
        dependsOn = it.dependsOn
    }

    doLast {
        tasks.each {
            println "${name} -> ${it.path}"
            it.execute()
        }
    }

}