import java.sql.ResultSet

apply plugin: 'sktools-dbtools-plugin'

// properties for substituering
def filterProperties = [
        db_username: db_username,
        db_schema: db_username,
]

configureDatabasePlugin {
    useDrivers libraries.ojdbc

    project.ext.tns = "${db_sid}_${db_hostname}"

    toolset(name: '', type: 'oracle', prefix: '') {
        sqlTask('purge', sqlFile: 'src/main/sql/oracle/schema/Purge.sql')
        sqlTask('createSchema', sqlFile: 'src/main/sql/oracle/schema/CreateSchema.sql') { mustRunAfter 'purge', 'historikkUpdatePackageSnapshotTime' }
        sqlTask('createSchemaTestStandAlone', sqlFile: 'src/main/sql/oracle/schema/CreateSchemaTestStandAlone.sql') { mustRunAfter 'createSchema' }
        sqlTask('createSchemaTest', sqlFile: 'src/main/sql/oracle/schema/CreateSchemaTest.sql') { mustRunAfter 'createSchema' }
        sqlTask('createSchemaTest2', sqlFile: 'src/main/sql/oracle/schema/CreateSchemaTest2.sql') { mustRunAfter 'createSchema' }
        sqlTask('tableSequence', sqlFile: 'src/main/sql/oracle/data/TableSequence.sql') { mustRunAfter 'createSchema' }
        sqlTask('loadTestdata', sqlFile: 'src/main/sql/oracle/data/LoadTestdata.sql') { mustRunAfter 'createSchema', 'createSchemaTestStandAlone', 'createSchemaTest', 'createSchemaTest2' }

        properties = project.properties

        credentials.username = db_username
        credentials.password = db_username
        url = "jdbc:oracle:thin:@${db_hostname}:${db_port}:${db_sid}"
    }

    /**
     * Toolset for SYSTEM-bruker
     */
    toolset(name: 'sa', type: 'oracle', prefix: 'sa') {
        sqlTask('grant', sqlFile: 'src/main/sql/oracle/schema/GrantRole.sql', description: 'Denne må kjøres en gang før du får tilstrekkelige privilegier til å kjøre dbInit')

        properties = filterProperties

        credentials.username = admin_db_username
        credentials.password = admin_db_password
        url = "jdbc:oracle:thin:@${db_hostname}:${db_port}:${db_sid}"

    }

    /**
     * Template for tilleggelse av historikk
     */
    toolset(name: 'historikk', type: 'oracle', prefix: 'historikk') {
        //tasker for historikk mekanikk
        sqlTask('createSnapshotTrans', sqlFile: 'src/main/sql/oracle/historikk/CreateTemporaryTableSnapshotTrans.sql', failOnError: false) {
            //feiler ikke dersom tabell allerede finnes fra før
            mustRunAfter 'purge'
        }
        sqlTask('updatePackageSnapshotTime', sqlFile: 'src/main/sql/oracle/historikk/UpdatePackageSnapshotTime.sql') {
            dependsOn 'historikkCreateSnapshotTrans'
        }


        filterProperties = [
                DATA_CONVERT_TIMESTAMP: '2012-09-02 00:00:00.00',   //dato for dump av kildebase som skal materialiseres
        ]

        credentials.username = db_username
        credentials.password = db_username
        url = "jdbc:oracle:thin:@${db_hostname}:${db_port}:${db_sid}"

    }

}


task dbInit {
    description = 'Purger schema, oppretter schema og fyller inn testdata'

    dependsOn 'purge'
    dependsOn 'historikkUpdatePackageSnapshotTime'
    dependsOn 'createSchema'
    dependsOn 'createSchemaTestStandAlone'
    dependsOn 'createSchemaTest'
    dependsOn 'createSchemaTest2'
    dependsOn 'tableSequence'
    dependsOn 'loadTestdata'
    dependsOn 'applyHistorikk'

}

task applyHistorikk() {
    mustRunAfter 'loadTestdata', 'tableSequence'
    def tables = [
            'BUBBLE_W_ENTITY_COMPS', 'ENTITY_COMPONENT',
            'LISTOFENTITYCOMPONENTS', 'LISTOFENTITYCOMPONENTS__C',
            'SUBTYPEDBUBBLE', 'TEKSTFORSUBTYPE',
            'HISTSIMPLE', 'HISTWITHRELATION',
            'HISTORISKDBKODE',
    ]

    doLast {
        groovy.sql.Sql sql = groovy.sql.Sql.newInstance("jdbc:oracle:thin:@${db_hostname}:${db_port}:${db_sid}", db_username, db_password, 'oracle.jdbc.OracleDriver')

        println("connected to database: ${sql.connection.metaData.URL} [${sql.connection.metaData.userName}]")

        def findColumnNames = { String schema, String tableName ->
            def ret = []
            def resultSet = sql.properties.connection.metaData.getColumns(null, schema, tableName.toUpperCase(), null)
            while (resultSet.next()) {
                ret.add(resultSet.getString('COLUMN_NAME'))
            }
            resultSet.close()
//            println "${schema}.${tableName} -> ${ret.join(',')}"
            return ret
        }

        def findPKColumnNames = { String schema, String tableName ->
            def ret = []
            def resultSet = sql.properties.connection.metaData.getPrimaryKeys(null, schema, tableName.toUpperCase())
            while (resultSet.next()) {
                ret[resultSet.getInt('KEY_SEQ') - 1] = resultSet.getString('COLUMN_NAME')
            }
            resultSet.close()
//            println "!!!!!!!!PK ${schema}.${tableName} -> ${ret.join(',')}"
            return ret
        }

        def findForeignKeys = { String schema, tableName ->
            def ret = []
            sql.query("select constraint_name from all_constraints where r_owner = '${schema}' and constraint_type = 'R' and table_name='${tableName.toUpperCase()}'".toString()) { ResultSet rs ->
                while (rs.next()) {
                    ret.add(rs.getString(1))
                }
            }
            return ret
        }

        // Drop alle fremmednøkler på tabeller som skal få historikk (antar at ingen ikke-historiske tabeller har fremmednøkler til historiske tabeller)
        tables.each { String tableName ->
            findForeignKeys(db_username, tableName).each {
                sql.execute("ALTER TABLE ${tableName} DROP CONSTRAINT ${it}".toString())
            }
        }

        tables.each { String tableName ->
            def pkColumns = findPKColumnNames(db_username, tableName)
            def columnNames = findColumnNames(db_username, tableName)
            def filteredColumnNames = new ArrayList(columnNames)
            boolean hasHistoryColumns = filteredColumnNames.removeAll(['OPPDATERINGSDATO', 'SLUTTDATO', 'VERSJONID'])

            sql.execute("ALTER TABLE ${tableName} DROP PRIMARY KEY DROP INDEX".toString())
            sql.execute("ALTER TABLE ${tableName} RENAME TO ${tableName}_H".toString())
            if (!hasHistoryColumns) {
                sql.execute("""
                    ALTER TABLE ${tableName}_H ADD (
                        oppdateringsdato TIMESTAMP(6) DEFAULT sysdate NOT NULL,
                        sluttdato TIMESTAMP(6) DEFAULT timestamp'9999-01-01 00:00:00.00' NOT NULL,
                        versjonId NUMBER (19,0) DEFAULT 0 NOT NULL
                     )""".toString())
            }
            sql.execute("ALTER TABLE ${tableName}_H ADD CONSTRAINT ${tableName}_UQ UNIQUE(${pkColumns.join(', ')}, sluttdato)".toString())
            sql.execute("CREATE UNIQUE INDEX ${tableName}_IX ON  ${tableName}_H (${pkColumns.join(', ')}, oppdateringsdato, sluttdato)".toString())

            sql.execute("CREATE OR REPLACE VIEW ${tableName} AS SELECT * FROM ${tableName}_H WHERE oppdateringsdato<=snapshot_time.get_t AND (snapshot_time.get_t<sluttdato OR sluttdato=snapshot_time.get_t_current)".toString());

            sql.execute("""CREATE OR REPLACE TRIGGER T_${tableName} INSTEAD OF INSERT OR UPDATE OR DELETE ON ${tableName}
 FOR EACH ROW
  DECLARE
    T_TRANS TIMESTAMP := SNAPSHOT_TIME.GET_T_TRANS();
    T_END TIMESTAMP := SNAPSHOT_TIME.GET_T_CURRENT();
    ANT NUMBER(10,0);
    UPDATE_FEIL EXCEPTION;
  BEGIN

  IF snapshot_time.GeT_T() <> t_End THEN
    RAISE_APPLICATION_ERROR(-20100, 'Modifikasjon mot historikk-data fungerer kun med t satt til t_CURRENT');
  END IF;

  IF INSERTING THEN
    INSERT INTO ${tableName}_H(${filteredColumnNames.collect {it}.join(', ')}, OPPDATERINGSDATO, SLUTTDATO, VERSJONID)
                       VALUES (${filteredColumnNames.collect {':NEW.' + it}.join(', ')}, T_TRANS, T_END, 1);
  ELSIF UPDATING THEN
    SELECT COUNT(*) INTO ANT FROM ${tableName}_H WHERE ${pkColumns.collect {it + '=:NEW.' + it}.join(' AND ')} AND SLUTTDATO = SNAPSHOT_TIME.GET_T_CURRENT();
    IF ANT = 0 THEN
      SELECT COUNT(*) INTO ANT FROM ${tableName}_H WHERE ${pkColumns.collect {it + '=:OLD.' + it}.join(' AND ')} AND SLUTTDATO = SNAPSHOT_TIME.GET_T_CURRENT();
      IF ANT = 1 THEN
        RAISE_APPLICATION_ERROR(-20003,'Det er ikke lov å endre primærnøkkelen på objekter i SKIF.');
      ELSE
        RAISE_APPLICATION_ERROR(-20002,'Det er ikke lov å kjøre update på noe som ikke har en current versjon! Skal ikke komme her da man ikke skal finne noe når man angir noe som ikke finnes!');
      END IF;
    ELSE
      IF :OLD.OPPDATERINGSDATO < T_TRANS THEN
        INSERT INTO ${tableName}_H(${filteredColumnNames.collect {it}.join(', ')}, OPPDATERINGSDATO, SLUTTDATO, VERSJONID)
                           VALUES (${filteredColumnNames.collect {':OLD.' + it}.join(',')}, :OLD.OPPDATERINGSDATO, T_TRANS, :OLD.VERSJONID);
        UPDATE ${tableName}_H SET VERSJONID = :OLD.VERSJONID+1
        WHERE ${pkColumns.collect {it + '=:OLD.' + it}.join(' AND ')} AND SLUTTDATO = T_END;
      END IF;
      UPDATE ${tableName}_H SET ${filteredColumnNames.collect {it + '=:NEW.' + it}.join(', ')}, OPPDATERINGSDATO=T_TRANS, SLUTTDATO=T_END, VERSJONID=VERSJONID
        WHERE ${pkColumns.collect {it + '=:OLD.' + it}.join(' AND ')} AND SLUTTDATO = T_END;
    END IF;
  ELSIF DELETING THEN
     IF :OLD.OPPDATERINGSDATO < T_TRANS THEN
        INSERT INTO ${tableName}_H(${filteredColumnNames.collect {it}.join(', ')}, OPPDATERINGSDATO, SLUTTDATO, VERSJONID)
                           VALUES (${filteredColumnNames.collect {':OLD.' + it}.join(', ')}, :OLD.OPPDATERINGSDATO, T_TRANS, :OLD.VERSJONID);
     END IF;
     DELETE FROM ${tableName}_H
        WHERE ${pkColumns.collect {it + '=:OLD.' + it}.join(' AND ')} AND SLUTTDATO = T_END;
  END IF;
END T_${tableName};""".toString())

        }
    }
}
