apply plugin: 'java'
apply plugin: 'sktools-weblogic-wsclient-plugin'

dependencies {
  weblogicProvided libraries.weblogic
  weblogicProvided libraries['tools.jar']
}

weblogicWsClient {
  webService {
    baseWar { project(path: ':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wswar', configuration: 'weblogic') }
    exceptionReusePackage 'no.statkart.skif.storetest.wsapi.exception'
    lastWsdl 'StoreServiceWS.wsdl'
  }
}


