plugins {
    id 'java'
    id 'sktools.wsimport'
}

configurations {
    wsdls
}

dependencies {
    wsdls project(path: ':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wswar', configuration: 'wsdls')
    jaxws libs.jaxws.tools

    implementation libs.bundles.jaxws.rt
}

// https://discuss.gradle.org/t/right-way-to-copy-contents-from-dependency-archives/7449/13
task importWsdls(type: Sync) {
    dependsOn configurations.wsdls

    into('META-INF/wsdls/skif-store') {
        from { configurations.wsdls.collect { zipTree(it) } }
    }

    into "$buildDir/wsdls/"
}

processResources.dependsOn importWsdls
sourceSets.main.resources.srcDir importWsdls.destinationDir

wsimport {
    exceptionReusePackage 'no.statkart.skif.storetest.wsapi.exception'
    lastWsdl 'META-INF/wsdls/skif-store/StoreServiceWS.wsdl'
}
