apply plugin: 'statkart-xjc-plugin'

dependencies {
    jaxb libraries.jaxb_xjc
    jaxb libraries.build_utils
}

statKartXjc {
    String jaxbSourceDir = 'src/main/schema'
    schema(jaxbSourceDir, '**/*.xsd', 'no.statkart.skif.skiftest.wsapi.domain no.statkart.skif.skiftest.domain')
    xjcLibraries = configurations.jaxb
}
