dependencies {
    compile project(':skif-store-test2:skif-store-test2-api')
//    compile project(':skif-store-test:skif-store-test2-wsmapping')
//    compile project(':skif-store-test:skif-store-test2-wsclient')

    provided libraries.jaxws_rt
    provided libraries.weblogic

    testCompile project(':skif-testsupport-common')
    testCompile project(':skif-store-test2:skif-store-test2-server')

    testCompile libraries.dbunit //optional library for testing
    testCompile libraries.unitils //optional library for testing

    //internal dependencies + optional deps to logging frameworks:
    testCompile project(':skif-config')
}
