-- Oppretter tabeller som brukes i storetest2-testprosjektet. Her skal det brukes mockupdata via mockup-rammeverk.

------------------------------------------------------------------------------------------------------------------------
-- Tabeller (uten koblinger)
------------------------------------------------------------------------------------------------------------------------

CREATE TABLE Eiendom (
    ID NUMBER(19,0) NOT NULL,
    EIENDOMSTYPEKODEID NUMBER(5,0) NOT NULL,
    CONSTRAINT PK_EIENDOM PRIMARY KEY (ID)
);

CREATE TABLE EiendomForEier (
    EIERID NUMBER(19,0) NOT NULL,
    EIENDOMID NUMBER(19,0) NOT NULL,
    CONSTRAINT PK_EIENDOMFOREIER PRIMARY KEY (EIERID, EIENDOMID)
);

CREATE TABLE Eier (
    ID NUMBER(19,0) NOT NULL,
    CONSTRAINT PK_EIER PRIMARY KEY (ID)
);

CREATE TABLE Endring (
    ID NUMBER(19,0) NOT NULL,
    CLASS VARCHAR2(255 CHAR) NOT NULL,
    ENDRINGSTYPE NUMBER(3,0),
    ENDRINGSTIDSPUNKT TIMESTAMP(6),
    BRUKERNAVN VARCHAR2(255 CHAR),
    ENDRETBUBBLEID NUMBER(19,0),
    CONSTRAINT PK_ENDRING PRIMARY KEY (ID)
);

CREATE TABLE Kodeliste2 (
    ID NUMBER(19,0) NOT NULL,
    KODETYPENAVN VARCHAR2(255 CHAR),
    KODEIDCLASSNAME VARCHAR2(255 CHAR),
    CONSTRAINT PK_KODELISTE2 PRIMARY KEY (ID)
);

CREATE TABLE Kodeliste2Loc (
    ID NUMBER(19,0) NOT NULL,
    NAVN VARCHAR2(255 CHAR),
    BESKRIVELSE VARCHAR2(255 CHAR),
    LOKALE VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT PK_KODELISTE2LOC PRIMARY KEY (ID, LOKALE)
);


CREATE TABLE ENTITY_COMPONENT (
    ID NUMBER(19,0) NOT NULL,
    OPPDATERINGSDATO TIMESTAMP(6),
    SLUTTDATO TIMESTAMP(6),
    VERSJONID NUMBER(19,0),
    VALUE VARCHAR2(255 CHAR),
    BUBBLEID NUMBER(19,0),
    CONSTRAINT PK_ENTITY_COMPONENT PRIMARY KEY (ID)
);
COMMENT ON TABLE ENTITY_COMPONENT IS 'Komponent for bobble';

CREATE TABLE BUBBLE_W_ENTITY_COMPS (
    ID NUMBER(19,0) NOT NULL,
    OPPDATERINGSDATO TIMESTAMP(6),
    SLUTTDATO TIMESTAMP(6),
    VERSJONID NUMBER(19,0),
    MAINENTITYCOMPONENT NUMBER(19,0) CONSTRAINT FK_BUBBLE_W_ENTITY_COMPS_1 REFERENCES ENTITY_COMPONENT(ID),
    CONSTRAINT PK_BUBBLE_W_ENTITY_COMPS PRIMARY KEY (ID)
);
COMMENT ON TABLE BUBBLE_W_ENTITY_COMPS IS 'Objekt med èn EntityComponent';


CREATE TABLE ListOfEntityComponents (
    ID NUMBER(19,0) NOT NULL,
    OPPDATERINGSDATO TIMESTAMP(6),
    SLUTTDATO TIMESTAMP(6),
    VERSJONID NUMBER(19,0),
    CONSTRAINT PK_LISTOFENTITYCOMPONENTS PRIMARY KEY (ID)
);
COMMENT ON TABLE LISTOFENTITYCOMPONENTS IS 'Bobble med liste av mange EntityComponent';

CREATE TABLE ListOfEntityComponents__C (
    ID NUMBER(19,0) NOT NULL,
    OPPDATERINGSDATO TIMESTAMP(6),
    SLUTTDATO TIMESTAMP(6),
    VERSJONID NUMBER(19,0),
    TEXTVALUE VARCHAR2(255 CHAR),
    LISTOFENTITYCOMPONENTSID NUMBER(19,0) CONSTRAINT FK_LISTENTITYCOMPONENT_1 REFERENCES LISTOFENTITYCOMPONENTS(ID),
    LISTINDEX NUMBER(10,0),
    CONSTRAINT PK_LISTOFENTITYCOMPONENTS__C PRIMARY KEY (ID)
);
COMMENT ON TABLE LISTOFENTITYCOMPONENTS__C IS 'Element i liste av komponenter for bobble';


CREATE TABLE Multirefererende (
    ID NUMBER(19,0) NOT NULL,
    CONSTRAINT PK_MULTIREFERERENDE PRIMARY KEY (ID)
);

--todo: forbedret navn
CREATE TABLE MultirefererendeKobling (
    MULTIREFERERENDEID NUMBER(19,0) NOT NULL,
    ROLLE VARCHAR2(255 CHAR) NOT NULL,
    TEKST VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT PK_MULTIREFERERENDEKOBLING PRIMARY KEY (MULTIREFERERENDEID, ROLLE, TEKST)
);

CREATE TABLE StoreTest2DbKode (
    ID NUMBER(19,0) NOT NULL,
    CLASS VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT PK_STORETEST2DBKODE PRIMARY KEY (ID)
);

--todo: forbedret navn
CREATE TABLE StoreTest2DbKodeLoc (
    ID NUMBER(19,0) NOT NULL,
    NAVN VARCHAR2(255 CHAR),
    BESKRIVELSE VARCHAR2(255 CHAR),
    LOKALE VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT PK_STORETEST2DBKODELOC PRIMARY KEY (ID, LOKALE)
);

CREATE TABLE SubTypedBubble (
    ID NUMBER(19,0) NOT NULL,
    CLASS VARCHAR2(255 CHAR) NOT NULL,
    TEXT VARCHAR2(255 CHAR),
    NUM NUMBER(10,0),
    CONSTRAINT PK_SUBTYPEDBUBBLE PRIMARY KEY (ID)
);

--todo: fobedret navn
CREATE TABLE TekstForSubtype (
    SUBTYPEDID NUMBER(19,0) NOT NULL,
    TEKST VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT PK_TEKSTFORSUBTYPE PRIMARY KEY (SUBTYPEDID, TEKST)
);



------------------------------------------------------------------------------------------------------------------------
-- Koblinger
------------------------------------------------------------------------------------------------------------------------

ALTER TABLE EIENDOMFOREIER ADD (
  CONSTRAINT FK_EIENDOMFOREIER_1 FOREIGN KEY (EIERID) REFERENCES EIER(ID),
  CONSTRAINT FK_EIENDOMFOREIER_2 FOREIGN KEY (EIENDOMID) REFERENCES EIENDOM(ID)
);

ALTER TABLE ENTITY_COMPONENT ADD (
  CONSTRAINT FK_ENTITY_COMPONENT_1 FOREIGN KEY (BUBBLEID) REFERENCES BUBBLE_W_ENTITY_COMPS(ID)
);

ALTER TABLE KODELISTE2LOC ADD (
  CONSTRAINT FK_KODELISTE2LOC_1 FOREIGN KEY (ID) REFERENCES KODELISTE2(ID)
);

ALTER TABLE MULTIREFERERENDEKOBLING ADD (
  CONSTRAINT FK_MULTIREFERERENDEKOBLING_1 FOREIGN KEY (MULTIREFERERENDEID) REFERENCES MULTIREFERERENDE(ID)
);

ALTER TABLE STORETEST2DBKODELOC ADD (
  CONSTRAINT FK_STORETEST2DBKODELOC_1 FOREIGN KEY (ID) REFERENCES STORETEST2DBKODE(ID)
);

ALTER TABLE TEKSTFORSUBTYPE ADD (
  CONSTRAINT FK_TEKSTFORSUBTYPE_1 FOREIGN KEY (SUBTYPEDID) REFERENCES SUBTYPEDBUBBLE(ID)
);
    
