plugins {
    id 'java'
}

dependencies {
    implementation project(':skif-store-test:skif-store-test-api')
    implementation project(':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wsmapping')
    runtimeOnly project(':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wsclient')

    implementation libs.bundles.jee
    implementation libs.c3p0
    implementation libs.ojdbc
    testImplementation project(':skif-testsupport-common')
    testImplementation project(':skif-store-test:skif-store-test-server')
    testImplementation project(':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wsclient')

    testImplementation libs.unitils //optional library for testing
    testImplementation libs.xstream // Brukes i test

    //internal dependencies + optional deps to logging frameworks:
    testImplementation project(':skif-config')
    testImplementation libs.logback.classic

}

task loadMockupData(type: JavaExec) {
    classpath = sourceSets.test.runtimeClasspath
    maxHeapSize = '1024m'
    mainClass = 'no.statkart.skif.storetest.mockup.LoadTestdata'
}
