dependencies {
    compile project(':skif-store-test:skif-store-test-api')
    compile project(':skif-store-test:skif-store-test-wsmapping')
    compile project(':skif-store-test:skif-store-test-wsclient')

    provided libraries.jaxws_rt
    provided libraries.weblogic

    testCompile project(':skif-config')
    testCompile project(':skif-testsupport-common')
    testCompile project(':skif-store-test:skif-store-test-server')
    testCompile project(path: ':skif-store-common', configuration: "testApi")
    testCompile project(path: ':skif-service-server', configuration: "tests")
    testCompile libraries.dbunit
}
