plugins {
    id 'java'
}

dependencies {
    testImplementation enforcedPlatform(project(':skif-internal-platform'))

    testImplementation project(':skif-testsupport-common')
    testImplementation(project(':skif-store-server')) {
        capabilities {
            requireCapability("no.statkart.skif:skif-store-server-oracle-support")
        }
    }

    testImplementation project(':skif-store-test:skif-store-test-api')
    testImplementation project(':skif-store-test:skif-store-test-server')
    testImplementation project(':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wsmapping')
    testImplementation project(':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wsclient')

    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.unitils:unitils-core'
    testImplementation 'com.thoughtworks.xstream:xstream'
    testImplementation 'ch.qos.logback:logback-classic'

    testRuntimeOnly libraries.jdbc
    testRuntimeOnly 'com.mchange:c3p0:0.9.5.2'
    testRuntimeOnly 'javax.transaction:jta'
    testRuntimeOnly 'javax.ejb:ejb-api'

    //internal dependencies + optional deps to logging frameworks:
    testRuntimeOnly project(':skif-config')
}

task loadMockupData(type: JavaExec) {
    classpath = sourceSets.test.runtimeClasspath
    maxHeapSize = '1024m'
    main = 'no.statkart.skif.storetest.mockup.LoadTestdata'
}
