plugins {
    id 'ear'
    id 'java-base'
}

def warMap = [
        ':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wswar': 'wsversioning/wsapi/v1',
        ':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wswar': 'wsversioning/wsapi/v2',
]

def ejbList = [
        ':skif-wsversioning:skif-wsversioning-server',
        ':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wscompat',
]

dependencies {
    ejbList.each {
        def p = project(it)
        deploy p
        earlib p
    }
    warMap.each {
        deploy project(path: it.key, configuration: 'war')
        earlib project(path: it.key, configuration: 'earlib')
    }

    earlib project(':skif-config')
}

libDirName = 'APP-INF/lib'
deploymentDescriptor {
    displayName = 'skif-wsversioning'
    version = '5'
    warMap.each {
        def p = project(it.key)
        webModule(p.name + '-' + p.version + '.war', it.value)
    }
}
