apply plugin: 'ear'
apply plugin: 'sktools-weblogic-deploy-plugin'

Map warMap = [
        ':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wswar': 'wsversioning/wsapi_v1',
        ':skif-wsversioning:skif-wsversioning-v2-ws:skif-wsversioning-v2-wswar': 'wsversioning/wsapi_v2',
]

List ejbList = [
        ':skif-wsversioning:skif-wsversioning-server',
        ':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wscompat',
]

dependencies {
    ejbList.each {
        def p = project(it)
        deploy p
        earlib p
    }
    warMap.each {
        def p = project(path: it.key, configuration: 'weblogic')
        deploy p
        earlib p
    }

    earlib project(':skif-config')
}

ear {
    libDirName 'APP-INF/lib'
    deploymentDescriptor {
        version = "5"
        displayName= "skif-wsversioning"
        warMap.each {
            def p = project(it.key)
            webModule(p.name + '-weblogic-' + p.version + ".war", it.value)
        }
    }

    exclude '*wswar*.jar'
}

weblogicDeploy {
  classpath = libraries.weblogic
  url(host: wls_deploy_hostname, port: wls_deploy_port, protocol: wls_deploy_protocol)
  targets = wls_deploy_targets
  username = wls_username
  password = wls_password

  file = ear
  name = archivesBaseName

  undeployTask('undeploy', description: "Undeployer ${name} til ${url}")

  deployTask('deploy', dependsOn: [undeployTask], description: "Deployer ${name} til ${url}") {
    timeout = 1200000
  }
}
