apply plugin: 'java'

dependencies {
    compile project(':skif-store-common')
    compile libraries.jodatime //optional dependency for jodatime funksjonalitet

    testCompile project(':skif-testsupport-common')

    //internal dependencies + optional deps to logging frameworks:
    testCompile project(':skif-config')
}