plugins {
    id 'java-library'
}

dependencies {
    api project(':skif-store-common')
    api project(':skif-service-common')
    api libraries.jsr305
    api libraries.jodatime

    testImplementation project(':skif-testsupport-common')

    //internal dependencies + optional deps to logging frameworks:
    testImplementation project(':skif-config')
}