logging:
  level:
    root: INFO
#    org.springframework.security: DEBUG
#    org.springframework.transaction: TRACE
#    no.statkart.skif.skiftest.config: DEBUG
#    org.springframework.jdbc.datasource: DEBUG
