//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.25 at 08:41:48 AM CEST 
//


package no.statkart.skif.skiftest.wsapi.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Java klasse for {http://skif.statkart.no/skiftest/wsapi/domain}SkifTestContext.
 * 
 * <p>
 * Schema definisjon:
 * 
 * <pre>
 * &lt;complexType name="SkifTestContext">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="systemVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="locale" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="locale4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @see no.statkart.skif.skiftest.domain.SkifTestContext
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SkifTestContext", propOrder = {
    "systemVersion",
    "locale",
    "locale4"
})
public class SkifTestContext {

    /**
     * 
     * 
     */
    @XmlElement(required = true)
    protected String systemVersion;
    /**
     * 
     * 
     */
    @XmlElement(required = true)
    protected String locale;
    /**
     * 
     * 
     */
    @XmlElement(required = true)
    protected String locale4;

    /**
     * 
     * @return
     */
    public String getSystemVersion() {
        return systemVersion;
    }

    /**
     * 
     * @param value
     */
    public void setSystemVersion(String value) {
        this.systemVersion = value;
    }

    /**
     * 
     * @return
     */
    public String getLocale() {
        return locale;
    }

    /**
     * 
     * @param value
     */
    public void setLocale(String value) {
        this.locale = value;
    }

    /**
     * 
     * @return
     */
    public String getLocale4() {
        return locale4;
    }

    /**
     * 
     * @param value
     */
    public void setLocale4(String value) {
        this.locale4 = value;
    }

}
