plugins {
    id 'sktools.wsgen'
    id 'singlevm-variant'
    id 'skinny-war'
}

configurations {
    wsdls { description = 'Zip med WSDL-er'; canBeConsumed = true; canBeResolved = false }
}

dependencies {
    implementation project(':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wscompat')
    implementation project(':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wsschema')
    implementation project(':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wsmapping')

    provided project(':skif-wsversioning:skif-wsversioning-server')
    provided libraries.jee
    provided libraries.jaxws_rt
}

task zipWsdls(type: Zip) {
    archiveAppendix = 'wsdls'
    from genWsdls
}

artifacts {
    wsdls zipWsdls
}
