apply plugin: 'java'
apply plugin: 'sktools-weblogic-wswar-plugin'

sourceSets.weblogic {
  java.srcDirs = ['src/main/java']
  resources.srcDirs = []
}


warWeblogic {
  from 'src/main/webapp'
}

configurations.weblogicProvided.extendsFrom configurations.provided

dependencies {
    compile project(':skif-wsversioning:skif-wsversioning-server')
    compile project(':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wsschema')
    compile project(':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wsmapping')

    provided libraries['tools.jar']
    provided libraries.weblogic

    testCompile project(':skif-testsupport-common')
    testRuntime project(':skif-config')
}
