<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema
        version="1.0"
        targetNamespace="http://skif.statkart.no/storetest/wsapi/domain/demo"
        xmlns:demons="http://skif.statkart.no/storetest/wsapi/domain/demo"
        xmlns:domainns="http://skif.statkart.no/storetest/wsapi/domain"
        xmlns:basetyperns="http://skif.statkart.no/storetest/wsapi/domain/basetyper"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified">

    <xs:import schemaLocation="domain.xsd" namespace="http://skif.statkart.no/storetest/wsapi/domain"/>
    <xs:import schemaLocation="basetyper.xsd" namespace="http://skif.statkart.no/storetest/wsapi/domain/basetyper"/>

    <!-- ================================================= -->
    <!-- Basisklasser                                      -->
    <!-- ================================================= -->

    <xs:complexType name="TestBubbleId">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubbleId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="TestBubble">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubble">
                <xs:sequence>
                    <xs:element name="text" type="xs:string" minOccurs="1" maxOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <xs:complexType name="FooId">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubbleId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Foo">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubble">
                <xs:sequence>
                    <xs:element name="nr" type="xs:long" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="navn" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="beginLifespanVersion" type="basetyperns:Timestamp" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="endLifespanVersion" type="basetyperns:Timestamp" minOccurs="1" maxOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="FooIdList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="demons:FooId"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="BarId">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubbleId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Bar">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubble">
                <xs:sequence>
                    <xs:element name="husnr" type="xs:long" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="bokstav" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="fooId" type="demons:FooId" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="bazId" type="demons:BazId" minOccurs="1" maxOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="BarIdList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="demons:BarId"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="BazId">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubbleId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Baz">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubble">
                <xs:sequence>
                    <xs:element name="text" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="fooId" type="demons:FooId" minOccurs="1" maxOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="BarFoosId">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubbleId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="RazId">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubbleId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Raz">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubble">
                <xs:sequence>
                    <xs:element name="text" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="razComponent" type="demons:RazComponent" minOccurs="1" maxOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="RazComponent">
        <xs:sequence>
            <xs:element name="compText" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="fooId" type="demons:FooId" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="BarFoos">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubble">
                <xs:sequence>
                    <xs:element name="text" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="barId" type="demons:BarId" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="FooIds" type="demons:FooIdList" minOccurs="1" maxOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="BarFoosIdList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="demons:BarFoosId"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Ikke  bobler -->

    <!--xs:complexType name="A">
        <xs:sequence>
            <xs:element name="text" type="xs:string" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="demons:A"/>
        </xs:sequence>
    </xs:complexType-->
</xs:schema>
