<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema
        version="1.0"
        targetNamespace="http://skif.statkart.no/storetest/wsapi/domain/kodeliste"
        xmlns:kodelistens="http://skif.statkart.no/storetest/wsapi/domain/kodeliste"
        xmlns:kodens="http://skif.statkart.no/storetest/wsapi/domain/kode"
        xmlns:domainns="http://skif.statkart.no/storetest/wsapi/domain"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified">

    <xs:import schemaLocation="domain.xsd" namespace="http://skif.statkart.no/storetest/wsapi/domain"/>
    <xs:import schemaLocation="kode.xsd" namespace="http://skif.statkart.no/storetest/wsapi/domain/kode"/>

    <xs:complexType name="KodelisteId">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubbleId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="KodelisteIdList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="kodelistens:KodelisteId"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Kodeliste">
        <xs:complexContent>
            <xs:extension base="domainns:StoreTestBubble">
                <xs:sequence>
                    <xs:element name="kodeIdClass" type="xs:string"/>
                    <xs:element name="navn" type="xs:string"/>
                    <xs:element name="beskrivelse" type="xs:string"/>
                    <xs:element name="kodeIds" type="kodens:KodeIdList"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="KodelisteList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="kodelistens:Kodeliste"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="KodelisteTransfer">
        <xs:sequence>
            <xs:element name="KodelisteIds" type="kodelistens:KodelisteIdList"/>
            <xs:element name="kodeIds" type="kodens:KodeIdList"/>
            <xs:element name="objects" type="domainns:StoreTestBubbleList"/>
        </xs:sequence>
    </xs:complexType>



</xs:schema>
