<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema
        version="1.0"
        targetNamespace="http://skif.statkart.no/storetest/wsapi/domain/kodeliste"
        xmlns:kodelistens="http://skif.statkart.no/storetest/wsapi/domain/kodeliste"
        xmlns:corens="http://skif.statkart.no/storetest/wsapi/domain"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified">

    <xs:import schemaLocation="core.xsd" namespace="http://skif.statkart.no/storetest/wsapi/domain"/>

    <xs:complexType name="KodeId">
        <xs:complexContent>
            <xs:extension base="corens:StoreTestBubbleId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Kode">
        <xs:complexContent>
            <xs:extension base="corens:StoreTestBubble">
                <xs:sequence>
                    <xs:element name="kodeverdi" type="xs:string"/>
                    <xs:element name="beskrivelse" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="KodeList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="kodelistens:Kode"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="KodeIdList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="kodelistens:KodeId"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="KodelisteId">
        <xs:complexContent>
            <xs:extension base="corens:StoreTestBubbleId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="KodelisteIdList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="kodelistens:KodelisteId"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Kodeliste">
        <xs:complexContent>
            <xs:extension base="corens:StoreTestBubble">
                <xs:sequence>
                    <xs:element name="kodeIdClass" type="xs:string"/>
                    <xs:element name="navn" type="xs:string"/>
                    <xs:element name="beskrivelse" type="xs:string"/>
                    <xs:element name="kodeIds" type="kodelistens:KodeIdList"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="KodelisteList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="kodelistens:Kodeliste"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="KodelisteTransfer">
        <xs:sequence>
            <xs:element name="KodelisteIds" type="kodelistens:KodelisteIdList"/>
            <xs:element name="kodeIds" type="kodelistens:KodeIdList"/>
            <xs:element name="objects" type="corens:StoreTestBubbleList"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="TestAEnumKodeId">
        <xs:complexContent>
            <xs:extension base="kodelistens:KodeId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="TestAEnumKode">
        <xs:complexContent>
            <xs:extension base="kodelistens:Kode">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <xs:complexType name="TestBEnumKodeId">
        <xs:complexContent>
            <xs:extension base="kodelistens:KodeId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="TestBEnumKode">
        <xs:complexContent>
            <xs:extension base="kodelistens:Kode">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="TestCEnumKodeId">
        <xs:complexContent>
            <xs:extension base="kodelistens:KodeId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="TestCEnumKode">
        <xs:complexContent>
            <xs:extension base="kodelistens:Kode">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="TestADbKodeId">
        <xs:complexContent>
            <xs:extension base="kodelistens:KodeId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="TestADbKode">
        <xs:complexContent>
            <xs:extension base="kodelistens:Kode">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="TestBDbKodeId">
        <xs:complexContent>
            <xs:extension base="kodelistens:KodeId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="TestBDbKode">
        <xs:complexContent>
            <xs:extension base="kodelistens:Kode">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="TestC1DbKodeId">
        <xs:complexContent>
            <xs:extension base="kodelistens:KodeId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="TestC1DbKode">
        <xs:complexContent>
            <xs:extension base="kodelistens:Kode">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TestC2DbKodeId">
        <xs:complexContent>
            <xs:extension base="kodelistens:KodeId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="TestC2DbKode">
        <xs:complexContent>
            <xs:extension base="kodelistens:Kode">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>
