<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema
        version="1.0"
        targetNamespace="http://skif.statkart.no/storetest/wsapi/domain"
        xmlns:storetestns="http://skif.statkart.no/storetest/wsapi/domain"
        xmlns:corens="http://skif.statkart.no/storetest/wsapi/domain"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified">

    <!-- ================================================= -->
    <!-- Domainklasser                                     -->
    <!-- ================================================= -->

    <xs:complexType name="TestBubbleId">
        <xs:complexContent>
            <xs:extension base="corens:StoreTestBubbleId">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="TestBubble">
        <xs:complexContent>
            <xs:extension base="corens:StoreTestBubble">
                <xs:sequence>
                    <xs:element name="text" type="xs:string" minOccurs="1" maxOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- Ikke  bobler -->

    <xs:complexType name="A">
        <xs:sequence>
            <xs:element name="text" type="xs:string" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AList">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="corens:A"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>
