apply plugin: 'sktools-weblogic-wswar-plugin'

sourceSets.weblogic {
    java.srcDirs = ['src/main/java']
    resources.srcDirs = []
}

warWeblogic {
  from 'src/main/webapp'
}

dependencies {
    weblogicCompile project(':skif-service-test:skif-service-test-server')
    weblogicCompile project(':skif-service-test:skif-service-test-v1-ws:skif-service-test-v1-wsmapping')

    weblogicProvided libraries['tools.jar']
    weblogicProvided libraries.weblogic
}


configurations {
    singlevm {
        description = 'En Jar-utgave for bruk i SingleVM'
        extendsFrom weblogic
    }
}


task jarSingleVm(type: Jar, dependsOn: project.tasks.warWeblogic.dependsOn) {
  classifier = 'singlevm'

  doFirst {
    from project.sourceSets.weblogic.output
  }
}

artifacts {
    singlevm jarSingleVm
}
