plugins {
    id 'sktools.wsgen'
    id 'sktools.provided'
}

configurations {
    war { description = 'War-artifaktet' }
    wsdls { description = 'Zip med WSDL-er' }
    earlib { extendsFrom implementation; description = 'Felles avhengheter i ear (skinny wars)'}
}

dependencies {
    implementation project(':skif-service-server')
    implementation project(':skif-service-test:skif-service-test-api')
    implementation project(':skif-service-test:skif-service-test-v1-ws:skif-service-test-v1-wsmapping')
    implementation project(':skif-service-test:skif-service-test-v1-ws:skif-service-test-v1-wsschema')

    provided libraries.jee
    provided libraries.jaxws_rt

    jaxws libraries.jaxws_tools
}

war {
    // Skinny war
    classpath = sourceSets.main.output
}

task zipWsdls(type: Zip) {
    archiveAppendix = 'wsdls'
    from genWsdls
}

artifacts {
    wsdls zipWsdls
    war project.war
}
