apply plugin: 'sktools-weblogic-wswar-plugin'

sourceSets.weblogic {
  java.srcDirs = ['src/main/java']
  resources.srcDirs = []
}


warWeblogic {
  from 'src/main/webapp'
}


dependencies {
    weblogicCompile project(':skif-store-test:skif-store-test-server')
    weblogicCompile project(':skif-store-test:skif-store-test-wsmapping')

    weblogicProvided libraries['tools.jar']
    weblogicProvided libraries.weblogic
}

//trenger dette for IntelliJ
project.idea.module {
    scopes.get('PROVIDED', [plus: [configurations.weblogicProvided], minus: []])
    scopes.get('COMPILE', [plus: [configurations.weblogic], minus: []])
}

