plugins {
    id 'sktools.wsgen'
    id 'sktools.wsdl-customizer'
    id 'sktools.provided'
}

configurations {
    war { description = 'War-artifaktet' }
    wsdls { description = 'Zip med WSDL-er' }
    earlib { extendsFrom implementation; description = 'Felles avhengheter i ear (skinny wars)'}
}

dependencies {
    if(hibernateVersion.equals("3.6")){
        implementation project(':skif-store-server:skif-store-server-hs36')
    }
    implementation project(':skif-store-test:skif-store-test-api')
    implementation project(':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wsmapping')
    implementation project(':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wsschema')

    provided libraries.jee

    originalSchemas project(path: ':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wsschema', configuration: 'schemas')
}

customizeWsdls {
    dependsOn genWsdls
    generatedWsdlAndSchemaFiles files(tasks.genWsdls.destinationDir).asFileTree.matching {
        include '**/*.wsdl', '**/*.xsd'
        exclude '**/*Internal*ServiceWS*'
    }
    includeNamespaces(
            'http://skif.statkart.no/storetest/wsapi/domain',
            'http://skif.statkart.no/storetest/wsapi/domain/basetyper',
            'http://skif.statkart.no/storetest/wsapi/domain/basic',
            'http://skif.statkart.no/storetest/wsapi/domain/component/composite',
            'http://skif.statkart.no/storetest/wsapi/domain/component/entity',
            'http://skif.statkart.no/storetest/wsapi/domain/component/historikk',
            'http://skif.statkart.no/storetest/wsapi/domain/demo/koder',
            'http://skif.statkart.no/storetest/wsapi/domain/endringslogg',
            'http://skif.statkart.no/storetest/wsapi/domain/kodeliste',
            'http://skif.statkart.no/storetest/wsapi/domain/koder',
            'http://skif.statkart.no/storetest/wsapi/domain/relation/uni/component/entity',
            'http://skif.statkart.no/storetest/wsapi/domain/relation/uni/direct',
            'http://skif.statkart.no/storetest/wsapi/exception',
            'http://skif.statkart.no/storetest/wsapi/service/testmapping',
    )

}

zipCustomizedWsdls {
    archiveClassifier = 'wsdls'
}


war {
    // Skinny war
    classpath = sourceSets.main.output

    // dokumentasjon for eksterne klienter
    from zipCustomizedWsdls
}

artifacts {
    wsdls zipCustomizedWsdls
    war project.war
}
