apply plugin: 'sktools-weblogic-wswar-plugin'

sourceSets.weblogic {
  java.srcDirs = ['src/main/java']
  resources.srcDirs = []
}


warWeblogic {
  from 'src/main/webapp'
}


dependencies {
    weblogicCompile project(':skif-store-test:skif-store-test-server')
    weblogicCompile project(':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wsmapping')

    weblogicProvided libraries['tools.jar']
    weblogicProvided libraries.weblogic
}
