plugins {
    id 'sktools.wsgen'
    id 'sktools.provided'
}

configurations {
    schemas { description = 'Configuration for consuming schemas' }
    war { description = 'War-artifaktet' }
    wsdls { description = 'Zip med WSDL-er' }
    earlib { extendsFrom implementation; description = 'Felles avhengheter i ear (skinny wars)'}
}

dependencies {
    if(hibernateVersion.equals("3.6")){
        implementation project(':skif-store-server:skif-store-server-hs36')
    }
    implementation project(':skif-store-test:skif-store-test-api')
    implementation project(':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wsmapping')
    implementation project(':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wsschema')

    provided libraries.jee

    schemas project(path: ':skif-store-test:skif-store-test-v1-ws:skif-store-test-v1-wsschema', configuration: 'schemas')
}

task zipWsdlsAndSchemas(type: Zip) { Task t ->
    baseName = 'schemas'

    dependsOn configurations.schemas
    from { configurations.schemas.files.collect { project.zipTree it } }

    from(genWsdls) {
        include '**/*.wsdl'
        include '**/*schema1.xsd'
    }

    includeEmptyDirs = false
}

war {
    // Skinny war
    classpath = sourceSets.main.output

    from zipWsdlsAndSchemas
}

task zipWsdls(type: Zip) {
    archiveAppendix = 'wsdls'
    from genWsdls
}

artifacts {
    wsdls zipWsdls
    war project.war
}
