plugins {
    id 'java-library'
    id 'maven-publish'
    id 'sktools.provided'
}

description = 'Inneholder service-rammeverk klasser for tjener'

java {
    registerFeature('springSupport') {
        usingSourceSet(sourceSets.main)
    }
}

configurations {
    sprigSupportApi.extendsFrom api
    springSupportImplementation.extendsFrom implementation
    springSupportCompileOnly.extendsFrom compileOnly
}

dependencies {
    api project(':skif-service-common')

    provided libraries.jee
    provided libraries.c3p0 // er kun brukt for intern testfunksjonalitet - burde kanskje ligge et annet sted
    provided libraries.jaxws_rt

    testImplementation project(':skif-config')
    testImplementation project(':skif-testsupport-common')
    testImplementation project(path: ':skif-service-common', configuration: 'testApi')
    testImplementation libraries.jdbc

    springSupportImplementation 'org.springframework:spring-context:5.3.12'
    springSupportImplementation 'org.springframework:spring-jdbc:5.3.12'
    springSupportImplementation 'org.aspectj:aspectjweaver:1.9.7'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
