plugins {
    id 'java-library'
    id 'maven-publish'
    id 'sktools.provided'
}

description = 'Inneholder service-rammeverk klasser for tjener'

dependencies {
    api project(':skif-service-common')

    provided libs.bundles.jee
    provided libs.bundles.jaxws.rt

    testImplementation project(':skif-config')
    testImplementation project(':skif-testsupport-common')
    testImplementation project(path: ':skif-service-common', configuration: 'testApi')
    
    if(System.getenv('ORA-DEBUG') == 'true'){
        testImplementation (libs.ojdbc.g){
             artifact {
                type = "jar"
             }
        }
    } else {
        testImplementation (libs.ojdbc){
            artifact {
                type = "jar"
            }
        }
    }
    testImplementation libs.c3p0
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}

def assertDependencies = tasks.register("assertDependencies") {
    doFirst {
        configurations.apiElements.getAllDependencies().each { Dependency dependency ->
            if (dependency instanceof SelfResolvingDependency) return
            throw new TaskExecutionException(it, new RuntimeException('Skal ikke ha api-avhengigheter: ' + dependency))
        }
    }
}
test.dependsOn assertDependencies //kjøres som en test
