apply plugin: 'statkart-wsclient-plugin'
apply plugin: 'statkart-javadoc-plugin'

dependencies {
    basewar project(':skif-service-test:skif-service-test-wswar')
}

wsClient {
    weblogicLibraries = configurations.weblogic

    fixExceptionsFor = [[
            exceptionPackageImport: 'import no.statkart.skif.skiftest.wsapi.exception.*;',
            exceptionPackage: 'no/statkart/skif/skiftest/wsapi/exception',
            exceptionFilePattern: '**/wsapi/service/**/*Exception.java',
            regexpMatch: /package no\.statkart\.skif\.skiftest\.wsapi\.service(\..+)*;/,
            regexpReplace: /package no\.statkart\.skif\.skiftest\.wsapi\.exception;/
    ]]
}
