plugins {
    id 'java'
}

dependencies {
    implementation project(':skif-service-test:skif-service-test-api')
    implementation project(':skif-service-test:skif-service-test-v1-ws:skif-service-test-v1-wsmapping')
    implementation project(':skif-service-test:skif-service-test-v1-ws:skif-service-test-v1-wsclient')

    testImplementation project(':skif-testsupport-common')

    //trenger denne avhengighet for testing av servicer
    testImplementation project(':skif-service-test:skif-service-test-server')
    testImplementation(project(':skif-service-test:skif-service-test-server')) {
        capabilities {
            requireCapability("${project.group}:skif-service-test-server-singlevm")
        }
    }

    testImplementation project(':skif-service-test:skif-service-test-v1-ws:skif-service-test-v1-wswar')

    //internal dependencies + optional deps to logging frameworks:
    testImplementation project(':skif-config')

    testImplementation libraries.jaxws_rt
}