plugins {
    id 'java'
}

dependencies {
    implementation project(':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wsmapping')
    implementation project(':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wsclient')

    implementation project(':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wscompat')
    implementation project(':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wswar')
    implementation project(':skif-wsversioning:skif-wsversioning-server')
    implementation libraries.jee

    testImplementation project(':skif-testsupport-common')
    testRuntimeOnly project(':skif-config')
}
