plugins {
    id 'java'
}

dependencies {
    testImplementation project(':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wsmapping')
    testImplementation project(':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wsclient')

    testImplementation project(':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wscompat')
    testImplementation project(':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wswar')
    testImplementation project(':skif-wsversioning:skif-wsversioning-server')

    testImplementation project(':skif-testsupport-common')
    testRuntimeOnly project(':skif-config')

    testRuntimeOnly 'javax.ejb:ejb-api'
}
