//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.25 at 08:41:48 AM CEST 
//


package no.statkart.skif.skiftest.wsapi.exception;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Java klasse for {http://skif.statkart.no/skiftest/wsapi/exception}ApplicationFaultInfo.
 * <br><p>
 * 
 *                     Felles klasse for alle typer av applikasjonsfeil.
 *                     Applikasjonsfeil skiller seg ifra {@link SystemFaultInfo systemfeil} på den måte da dette er feil som direkte skyldes applikasjons-spesifik logikk.
 *                     Med dette forstås brukerfeil så vel som logiske domene beskrenkninger applikasjonen definerer.
 *                     
 *                 
 * 
 * <p>
 * Schema definisjon:
 * 
 * <pre>
 * &lt;complexType name="ApplicationFaultInfo">
 *   &lt;complexContent>
 *     &lt;extension base="{http://skif.statkart.no/skiftest/wsapi/exception}ServiceFaultInfo">
 *       &lt;sequence>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @see no.statkart.skif.skiftest.wsapi.exception.ApplicationFaultInfo
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationFaultInfo")
@XmlSeeAlso({
    ValidationFaultInfo.class,
    FinderFaultInfo.class
})
public class ApplicationFaultInfo
    extends ServiceFaultInfo
{


}
