//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.25 at 08:41:48 AM CEST 
//


package no.statkart.skif.skiftest.wsapi.exception;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Java klasse for {http://skif.statkart.no/skiftest/wsapi/exception}ExceptionDetail.
 * <br><p>
 * 
 *                         Informasjon om exception oppstått på server med hirarki, stacktrace mm.
 *                     
 *                 
 * 
 * <p>
 * Schema definisjon:
 * 
 * <pre>
 * &lt;complexType name="ExceptionDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="className" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stackTraceElements" type="{http://skif.statkart.no/skiftest/wsapi/exception}StackTraceElementList"/>
 *         &lt;element name="cause" type="{http://skif.statkart.no/skiftest/wsapi/exception}ExceptionDetail"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @see no.statkart.skif.skiftest.wsapi.exception.ExceptionDetail
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExceptionDetail", propOrder = {
    "className",
    "message",
    "stackTraceElements",
    "cause"
})
public class ExceptionDetail {

    /**
     * Klassenavn for exception.
     * 
     */
    @XmlElement(required = true)
    protected String className;
    /**
     * Teknisk underliggende feilmeldingstekst.
     * 
     */
    @XmlElement(required = true)
    protected String message;
    /**
     * Stacktrace generert ifra system. Denne er kun brukt ved {@link SystemException systemfeil}.
     * 
     */
    @XmlElement(required = true)
    protected StackTraceElementList stackTraceElements;
    /**
     * Evt nøstet exception kan komme her.
     * 
     */
    @XmlElement(required = true, nillable = true)
    protected ExceptionDetail cause;

    /**
     * 
     * @return
     */
    public String getClassName() {
        return className;
    }

    /**
     * 
     * @param value
     */
    public void setClassName(String value) {
        this.className = value;
    }

    /**
     * 
     * @return
     */
    public String getMessage() {
        return message;
    }

    /**
     * 
     * @param value
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * 
     * @return
     */
    public StackTraceElementList getStackTraceElements() {
        return stackTraceElements;
    }

    /**
     * 
     * @param value
     */
    public void setStackTraceElements(StackTraceElementList value) {
        this.stackTraceElements = value;
    }

    /**
     * 
     * @return
     */
    public ExceptionDetail getCause() {
        return cause;
    }

    /**
     * 
     * @param value
     */
    public void setCause(ExceptionDetail value) {
        this.cause = value;
    }

}
