//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.25 at 08:41:48 AM CEST 
//


package no.statkart.skif.skiftest.wsapi.exception;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Java klasse for {http://skif.statkart.no/skiftest/wsapi/exception}FinderFaultInfo.
 * <br><p>
 * 
 *                     Felles klasse for feil ved oppslag der datagrunnlag ikke er i henhold til kriterier.
 *                     
 *                 
 * 
 * <p>
 * Schema definisjon:
 * 
 * <pre>
 * &lt;complexType name="FinderFaultInfo">
 *   &lt;complexContent>
 *     &lt;extension base="{http://skif.statkart.no/skiftest/wsapi/exception}ApplicationFaultInfo">
 *       &lt;sequence>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @see no.statkart.skif.skiftest.wsapi.exception.FinderFaultInfo
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FinderFaultInfo")
public class FinderFaultInfo
    extends ApplicationFaultInfo
{


}
