//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.25 at 08:41:48 AM CEST 
//


package no.statkart.skif.skiftest.wsapi.exception;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Java klasse for {http://skif.statkart.no/skiftest/wsapi/exception}ImplementationFaultInfo.
 * <br><p>
 * 
 *                         Feil som oppstår i kode enten på server, eller på bagrunn av feil i kall fra klient.
 *                      
 *                 
 * 
 * <p>
 * Schema definisjon:
 * 
 * <pre>
 * &lt;complexType name="ImplementationFaultInfo">
 *   &lt;complexContent>
 *     &lt;extension base="{http://skif.statkart.no/skiftest/wsapi/exception}SystemFaultInfo">
 *       &lt;sequence>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @see no.statkart.skif.skiftest.wsapi.exception.ImplementationFaultInfo
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImplementationFaultInfo")
public class ImplementationFaultInfo
    extends SystemFaultInfo
{


}
