//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.25 at 08:41:48 AM CEST 
//


package no.statkart.skif.skiftest.wsapi.exception;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the no.statkart.skif.skiftest.wsapi.exception package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FinderException_QNAME = new QName("http://skif.statkart.no/skiftest/wsapi/exception", "FinderException");
    private final static QName _ValidationException_QNAME = new QName("http://skif.statkart.no/skiftest/wsapi/exception", "ValidationException");
    private final static QName _SystemException_QNAME = new QName("http://skif.statkart.no/skiftest/wsapi/exception", "SystemException");
    private final static QName _OperationalException_QNAME = new QName("http://skif.statkart.no/skiftest/wsapi/exception", "OperationalException");
    private final static QName _ImplementationException_QNAME = new QName("http://skif.statkart.no/skiftest/wsapi/exception", "ImplementationException");
    private final static QName _SimpleException_QNAME = new QName("http://skif.statkart.no/skiftest/wsapi/exception", "SimpleException");
    private final static QName _ServiceException_QNAME = new QName("http://skif.statkart.no/skiftest/wsapi/exception", "ServiceException");
    private final static QName _ApplicationException_QNAME = new QName("http://skif.statkart.no/skiftest/wsapi/exception", "ApplicationException");
    private final static QName _SimpleNonMappedException_QNAME = new QName("http://skif.statkart.no/skiftest/wsapi/exception", "SimpleNonMappedException");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: no.statkart.skif.skiftest.wsapi.exception
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SimpleNonMappedFaultInfo }
     * 
     */
    public SimpleNonMappedFaultInfo createSimpleNonMappedFaultInfo() {
        return new SimpleNonMappedFaultInfo();
    }

    /**
     * Create an instance of {@link ExceptionDetail }
     * 
     */
    public ExceptionDetail createExceptionDetail() {
        return new ExceptionDetail();
    }

    /**
     * Create an instance of {@link SystemFaultInfo }
     * 
     */
    public SystemFaultInfo createSystemFaultInfo() {
        return new SystemFaultInfo();
    }

    /**
     * Create an instance of {@link ServiceFaultInfo }
     * 
     */
    public ServiceFaultInfo createServiceFaultInfo() {
        return new ServiceFaultInfo();
    }

    /**
     * Create an instance of {@link ApplicationFaultInfo }
     * 
     */
    public ApplicationFaultInfo createApplicationFaultInfo() {
        return new ApplicationFaultInfo();
    }

    /**
     * Create an instance of {@link OperationalFaultInfo }
     * 
     */
    public OperationalFaultInfo createOperationalFaultInfo() {
        return new OperationalFaultInfo();
    }

    /**
     * Create an instance of {@link StackTraceElement }
     * 
     */
    public StackTraceElement createStackTraceElement() {
        return new StackTraceElement();
    }

    /**
     * Create an instance of {@link ImplementationFaultInfo }
     * 
     */
    public ImplementationFaultInfo createImplementationFaultInfo() {
        return new ImplementationFaultInfo();
    }

    /**
     * Create an instance of {@link SimpleFaultInfo }
     * 
     */
    public SimpleFaultInfo createSimpleFaultInfo() {
        return new SimpleFaultInfo();
    }

    /**
     * Create an instance of {@link StackTraceElementList }
     * 
     */
    public StackTraceElementList createStackTraceElementList() {
        return new StackTraceElementList();
    }

    /**
     * Create an instance of {@link ValidationFaultInfo }
     * 
     */
    public ValidationFaultInfo createValidationFaultInfo() {
        return new ValidationFaultInfo();
    }

    /**
     * Create an instance of {@link FinderFaultInfo }
     * 
     */
    public FinderFaultInfo createFinderFaultInfo() {
        return new FinderFaultInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FinderFaultInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skif.statkart.no/skiftest/wsapi/exception", name = "FinderException")
    public JAXBElement<FinderFaultInfo> createFinderException(FinderFaultInfo value) {
        return new JAXBElement<FinderFaultInfo>(_FinderException_QNAME, FinderFaultInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidationFaultInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skif.statkart.no/skiftest/wsapi/exception", name = "ValidationException")
    public JAXBElement<ValidationFaultInfo> createValidationException(ValidationFaultInfo value) {
        return new JAXBElement<ValidationFaultInfo>(_ValidationException_QNAME, ValidationFaultInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SystemFaultInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skif.statkart.no/skiftest/wsapi/exception", name = "SystemException")
    public JAXBElement<SystemFaultInfo> createSystemException(SystemFaultInfo value) {
        return new JAXBElement<SystemFaultInfo>(_SystemException_QNAME, SystemFaultInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OperationalFaultInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skif.statkart.no/skiftest/wsapi/exception", name = "OperationalException")
    public JAXBElement<OperationalFaultInfo> createOperationalException(OperationalFaultInfo value) {
        return new JAXBElement<OperationalFaultInfo>(_OperationalException_QNAME, OperationalFaultInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImplementationFaultInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skif.statkart.no/skiftest/wsapi/exception", name = "ImplementationException")
    public JAXBElement<ImplementationFaultInfo> createImplementationException(ImplementationFaultInfo value) {
        return new JAXBElement<ImplementationFaultInfo>(_ImplementationException_QNAME, ImplementationFaultInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleFaultInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skif.statkart.no/skiftest/wsapi/exception", name = "SimpleException")
    public JAXBElement<SimpleFaultInfo> createSimpleException(SimpleFaultInfo value) {
        return new JAXBElement<SimpleFaultInfo>(_SimpleException_QNAME, SimpleFaultInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceFaultInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skif.statkart.no/skiftest/wsapi/exception", name = "ServiceException")
    public JAXBElement<ServiceFaultInfo> createServiceException(ServiceFaultInfo value) {
        return new JAXBElement<ServiceFaultInfo>(_ServiceException_QNAME, ServiceFaultInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplicationFaultInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skif.statkart.no/skiftest/wsapi/exception", name = "ApplicationException")
    public JAXBElement<ApplicationFaultInfo> createApplicationException(ApplicationFaultInfo value) {
        return new JAXBElement<ApplicationFaultInfo>(_ApplicationException_QNAME, ApplicationFaultInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleNonMappedFaultInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skif.statkart.no/skiftest/wsapi/exception", name = "SimpleNonMappedException")
    public JAXBElement<SimpleNonMappedFaultInfo> createSimpleNonMappedException(SimpleNonMappedFaultInfo value) {
        return new JAXBElement<SimpleNonMappedFaultInfo>(_SimpleNonMappedException_QNAME, SimpleNonMappedFaultInfo.class, null, value);
    }

}
