//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.25 at 08:41:48 AM CEST 
//


package no.statkart.skif.skiftest.wsapi.exception;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Java klasse for {http://skif.statkart.no/skiftest/wsapi/exception}OperationalFaultInfo.
 * <br><p>
 * 
 *                         Operasjonelle feil har feilkilder som stammer utelukkende ifra det utenpåliggende miljøet systemet kjører i.
 *                         Typiske eksempler er at serveren går tom for diskplass, eller at forbindelsen med databasen blir borte.
 *                      
 *                 
 * 
 * <p>
 * Schema definisjon:
 * 
 * <pre>
 * &lt;complexType name="OperationalFaultInfo">
 *   &lt;complexContent>
 *     &lt;extension base="{http://skif.statkart.no/skiftest/wsapi/exception}SystemFaultInfo">
 *       &lt;sequence>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @see no.statkart.skif.skiftest.wsapi.exception.OperationalFaultInfo
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperationalFaultInfo")
public class OperationalFaultInfo
    extends SystemFaultInfo
{


}
