//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.25 at 08:41:48 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://skif.statkart.no/skiftest/wsapi/exception", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package no.statkart.skif.skiftest.wsapi.exception;
