//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.25 at 08:41:48 AM CEST 
//


package no.statkart.skif.skiftest.wsapi.exception;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Java klasse for {http://skif.statkart.no/skiftest/wsapi/exception}ServiceFaultInfo.
 * <br><p>
 * 
 *                     Abstrakt fellestype for alle service feil som kan oppstå.
 *                     <p/>
 *                     Feiltyper deles strengt inn i {@link ApplicationFaultInfo applikasjonsfeil} og {@link SystemFaultInfo systemfeil}.
 *                     
 *                 
 * 
 * <p>
 * Schema definisjon:
 * 
 * <pre>
 * &lt;complexType name="ServiceFaultInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="feilkode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="feilkodebeskrivelse" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stackTraceText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="exceptionDetail" type="{http://skif.statkart.no/skiftest/wsapi/exception}ExceptionDetail"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @see no.statkart.skif.skiftest.wsapi.exception.ServiceFaultInfo
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceFaultInfo", propOrder = {
    "feilkode",
    "feilkodebeskrivelse",
    "stackTraceText",
    "exceptionDetail"
})
@XmlSeeAlso({
    SystemFaultInfo.class,
    ApplicationFaultInfo.class
})
public class ServiceFaultInfo {

    /**
     * Kort kode for feil. Er i hovedsak tiltenkt applikasjonsfeil.
     * 
     */
    @XmlElement(required = true)
    protected String feilkode;
    /**
     * Tekstlig beskrivelse av {@link #feilkode feilkode}.
     * 
     */
    @XmlElement(required = true)
    protected String feilkodebeskrivelse;
    /**
     * Formatert, komplett, stacktrace som kan innrapporteres. Denne er kun brukt ved {@link SystemException systemfeil}.
     * 
     */
    @XmlElement(required = true)
    protected String stackTraceText;
    /**
     * Maskinlesbar informasjon om exception.
     * 
     */
    @XmlElement(required = true)
    protected ExceptionDetail exceptionDetail;

    /**
     * 
     * @return
     */
    public String getFeilkode() {
        return feilkode;
    }

    /**
     * 
     * @param value
     */
    public void setFeilkode(String value) {
        this.feilkode = value;
    }

    /**
     * 
     * @return
     */
    public String getFeilkodebeskrivelse() {
        return feilkodebeskrivelse;
    }

    /**
     * 
     * @param value
     */
    public void setFeilkodebeskrivelse(String value) {
        this.feilkodebeskrivelse = value;
    }

    /**
     * 
     * @return
     */
    public String getStackTraceText() {
        return stackTraceText;
    }

    /**
     * 
     * @param value
     */
    public void setStackTraceText(String value) {
        this.stackTraceText = value;
    }

    /**
     * 
     * @return
     */
    public ExceptionDetail getExceptionDetail() {
        return exceptionDetail;
    }

    /**
     * 
     * @param value
     */
    public void setExceptionDetail(ExceptionDetail value) {
        this.exceptionDetail = value;
    }

}
