//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.25 at 08:41:48 AM CEST 
//


package no.statkart.skif.skiftest.wsapi.exception;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Java klasse for {http://skif.statkart.no/skiftest/wsapi/exception}SimpleNonMappedFaultInfo.
 * 
 * <p>
 * Schema definisjon:
 * 
 * <pre>
 * &lt;complexType name="SimpleNonMappedFaultInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="infoField" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @see no.statkart.skif.skiftest.wsapi.exception.SimpleNonMappedFaultInfo
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimpleNonMappedFaultInfo", propOrder = {
    "infoField"
})
public class SimpleNonMappedFaultInfo {

    /**
     * 
     * 
     */
    @XmlElement(required = true, nillable = true)
    protected String infoField;

    /**
     * 
     * @return
     */
    public String getInfoField() {
        return infoField;
    }

    /**
     * 
     * @param value
     */
    public void setInfoField(String value) {
        this.infoField = value;
    }

}
