//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.25 at 08:41:48 AM CEST 
//


package no.statkart.skif.skiftest.wsapi.exception;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Java klasse for {http://skif.statkart.no/skiftest/wsapi/exception}StackTraceElementList.
 * 
 * <p>
 * Schema definisjon:
 * 
 * <pre>
 * &lt;complexType name="StackTraceElementList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="item" type="{http://skif.statkart.no/skiftest/wsapi/exception}StackTraceElement" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StackTraceElementList", propOrder = {
    "item"
})
public class StackTraceElementList {

    /**
     * 
     * 
     */
    protected List<StackTraceElement> item;

    /**
     * 
     * @return
     */
    public List<StackTraceElement> getItem() {
        if (item == null) {
            item = new ArrayList<StackTraceElement>();
        }
        return this.item;
    }

}
