//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.25 at 08:41:48 AM CEST 
//


package no.statkart.skif.skiftest.wsapi.exception;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Java klasse for {http://skif.statkart.no/skiftest/wsapi/exception}StackTraceElement.
 * 
 * <p>
 * Schema definisjon:
 * 
 * <pre>
 * &lt;complexType name="StackTraceElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="declaringClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="methodName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lineNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @see no.statkart.skif.skiftest.wsapi.exception.StackTraceElement
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StackTraceElement", propOrder = {
    "declaringClass",
    "methodName",
    "fileName",
    "lineNumber"
})
public class StackTraceElement {

    /**
     * 
     * 
     */
    @XmlElement(required = true)
    protected String declaringClass;
    /**
     * 
     * 
     */
    @XmlElement(required = true)
    protected String methodName;
    /**
     * 
     * 
     */
    @XmlElement(required = true, nillable = true)
    protected String fileName;
    /**
     * 
     * 
     */
    protected int lineNumber;

    /**
     * 
     * @return
     */
    public String getDeclaringClass() {
        return declaringClass;
    }

    /**
     * 
     * @param value
     */
    public void setDeclaringClass(String value) {
        this.declaringClass = value;
    }

    /**
     * 
     * @return
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * 
     * @param value
     */
    public void setMethodName(String value) {
        this.methodName = value;
    }

    /**
     * 
     * @return
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * 
     * @param value
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * 
     * @return
     */
    public int getLineNumber() {
        return lineNumber;
    }

    /**
     * 
     * @param value
     */
    public void setLineNumber(int value) {
        this.lineNumber = value;
    }

}
