//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.25 at 08:41:48 AM CEST 
//


package no.statkart.skif.skiftest.wsapi.exception;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Java klasse for {http://skif.statkart.no/skiftest/wsapi/exception}SystemFaultInfo.
 * <br><p>
 * 
 *                     Felles klasse for alle typer systemfeil. <br />
 *                     Systemfeil skiller seg ifra {@link ApplicationFaultInfo applikasjonsfeil} på den måte da
 *                     dette er feil som oppstår i og på grunn av systemet. Eksempler er implementasjonsfeil og feil som kan oppstå når deler av det fysiske miljøet rundt ikke er tigjengelig.
 *                     <p>
 *                     Feil skilles grovt inn i
 *                         {@link OperationalFaultInfo operasjonelle feil} og
 *                         {@link ImplementationFaultInfo implementasjonsfeil}.
 *                      
 *                 
 * 
 * <p>
 * Schema definisjon:
 * 
 * <pre>
 * &lt;complexType name="SystemFaultInfo">
 *   &lt;complexContent>
 *     &lt;extension base="{http://skif.statkart.no/skiftest/wsapi/exception}ServiceFaultInfo">
 *       &lt;sequence>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @see no.statkart.skif.skiftest.wsapi.exception.SystemFaultInfo
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SystemFaultInfo")
@XmlSeeAlso({
    ImplementationFaultInfo.class,
    OperationalFaultInfo.class
})
public class SystemFaultInfo
    extends ServiceFaultInfo
{


}
