plugins {
    id 'java-library'
}

configurations {
    client
}

dependencies {
    api project(':skif-store-test:skif-store-test-api')
    api project(':skif-store-server')

    compileOnly libraries.jee
    compileOnly libraries.c3p0
    compileOnly libraries.jdbc

    testImplementation project(':skif-testsupport-common')

    testImplementation libraries.jee
    testImplementation libraries.c3p0
    testImplementation libraries.jdbc
    // internal dependencies + optional deps to logging frameworks:
    testImplementation project(':skif-config')
}
