plugins {
    id 'java-library'
    id 'sktools.provided'
}

configurations {
    client
}

dependencies {
    api project(':skif-store-test:skif-store-test-api')
    api project(':skif-store-server')

    provided libs.bundles.jee
    provided libs.c3p0
        if(System.getenv('ORA-DEBUG') == 'true'){
        provided (libs.ojdbc.g){
             artifact {
                type = "jar"
             }
        }
    } else {
        provided (libs.ojdbc){
            artifact {
                type = "jar"
            }
        }
    }

    testImplementation project(':skif-testsupport-common')

    // internal dependencies + optional deps to logging frameworks:
    testImplementation project(':skif-config')
}
