configurations {
    client
}

dependencies {
    compile project(':skif-store-server')
    if(hibernateVersion.equals("3.2")) {
      compile project(':skif-store-server-hs32')
    } else if(hibernateVersion.equals("3.6")){
      compile project(':skif-store-server-hs36')
    }
    compile project(':skif-store-test:skif-store-test-api')
    provided libraries.weblogic

    testCompile project(':skif-config')
    testCompile project(':skif-testsupport-common')
}

task clientJar(type: Jar) {
    appendix = 'client'
    from sourceSets.main.classes
}

artifacts {
//   archives clientJar
}
