apply plugin: 'java'

dependencies {
    compile project(':skif-service-test:skif-service-test-api')
    provided project(':skif-service-test:skif-service-test-v1-ws:skif-service-test-v1-wsschema')

    testCompile project(':skif-testsupport-common')
    testCompile libraries.unitils //optional library for testing

    //internal dependencies + optional deps to logging frameworks:
    testCompile project(':skif-config')

}