import no.statkart.gradle.util.DependencyUtil

apply plugin: 'statkart-weblogic-wswar-plugin'

dependencies {
    compile project(':skif-service-test:skif-service-test-server')
    compile project(':skif-service-test:skif-service-test-wsmapping')

    provided libraries.weblogic
    provided files(DependencyUtil.getJavaTools())
}

statKartWeblogicWsWar {
    sourceDir = 'src/main/java'
    classpath = configurations.compile + configurations.provided
    weblogicLibraries = configurations.weblogic
}

configurations {
    singlevm {
        description = 'En Jar-utgave for bruk i SingleVM'
        extendsFrom runtime
    }
}

task singleVmJar(type: Jar, dependsOn: weblogicWsWar) {
    from new File(new File(new File(weblogicWsWar.buildEarDirFile, weblogicWsWar.jswcWarDirName), 'WEB-INF'), 'classes')
}

artifacts {
    singlevm singleVmJar
}
