apply plugin: 'java'
apply plugin: 'sktools-weblogic-wsclient-plugin'

dependencies {
  weblogicProvided libraries.weblogic_tools
  weblogicProvided libraries['tools.jar']
}

weblogicWsClient {
  webService {
    baseWar { project(path: ':skif-wsversioning:skif-wsversioning-v1-ws:skif-wsversioning-v1-wswar', configuration: 'weblogic') }
    exceptionReusePackage 'no.statkart.skif.wsversioning.wsapi.v1.exception'
  }
}


