plugins {
    id 'java-platform'
    id 'maven-publish'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.javaPlatform
        }
    }
}

description = "Platform BOM for aligning SKIF dependencies and security patches for TomEE/Tomcat!"

javaPlatform {
    allowDependencies()
}

dependencies {
    constraints {
        api libs.tomee.embedded
        api libs.tomee.security

        api libs.jakarta.ee.bom
        api libs.tomee.plus.bom
        api libs.tomee.plus.api.bom

        api project(":skif-service-common")
        api project(":skif-service-server")
        api project(":skif-store-common")
        api project(":skif-store-server")
        api project(":skif-testsupport-common")

        //security fixes for Apache Tomcat when waiting for Apache TomEE fix
        [
            "tomcat-api",
            "tomcat-annotations-api",
            "tomcat-catalina",
            "tomcat-catalina-ha",
            "tomcat-coyote",
            "tomcat-dbcp",
            "tomcat-el-api",
            "tomcat-jaspic-api",
            "tomcat-jasper",
            "tomcat-jasper-el",
            "tomcat-jdbc",
            "tomcat-jni",
            "tomcat-jsp-api",
            "tomcat-servlet-api",
            "tomcat-tribes",
            "tomcat-util",
            "tomcat-util-scan",
            "tomcat-websocket",
            "tomcat-websocket-api",
            "tomcat-websocket-client-api",
            "tomcat-juli",
        ].each { tomcatModule ->
            runtime("org.apache.tomcat:${tomcatModule}:${libs.versions.tomee.tomcat.patch.get()}") because(
                "Temporary security override until TomEE updates Tomcat"
            )
        }
    }
}
