configurations {
    client
}

dependencies {
    compile project(':skif-service-server')
    compile project(':skif-service-test:skif-service-test-api')
}




task clientJar(type: Jar) {
    appendix = 'client'
    from sourceSets.main.classes
}

artifacts {
//   archives clientJar
}

task xx << {
    configurations.provided.allDependencies {
            println "name"
            println it.getClass()
            println it.getName()
            return true
        }.each {println it}

}
