plugins {
    id 'java-library'
}

dependencies {
    api project(':skif-service-server')
    api project(':skif-service-test:skif-service-test-api')

    compileOnly libs.bundles.jee
    compileOnly libs.c3p0
    testImplementation project(':skif-testsupport-common')

    //internal dependencies + optional deps to logging frameworks:
    testImplementation project(':skif-config')
    testImplementation libs.bundles.jee
    testImplementation libs.c3p0
    if (System.getenv('ORA-DEBUG') == 'true') {
        compileOnly libs.ojdbcg
        testImplementation(libs.ojdbcg)

    } else {
        compileOnly libs.ojdbc
        testImplementation(libs.ojdbc)
    }
}
