apply plugin: 'java'

dependencies {
    compile project(':skif-service-server')
    compile project(':skif-service-test:skif-service-test-api')
    compile libraries.c3p0
    provided libraries.weblogic
    provided libraries.jdbc

    testCompile project(':skif-testsupport-common')

    //internal dependencies + optional deps to logging frameworks:
    testCompile project(':skif-config')
}
