name: Build and Publish

on:
    push:
        branches:
            - '**'
    workflow_dispatch:

env:
    MAJOR_VERSION: 4

jobs:
    calculate-version:
        name: Calculate Version
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.version-string.outputs.version }}

        steps:
            -   name: Generate version string
                id: version-string
                shell: bash
                run: |
                    version="${{ env.MAJOR_VERSION }}.$(date -u '+%Y.%m.%d-%H.%M')-$(echo "${GITHUB_SHA}" | cut -c1-7)"
                    echo "version=${version}" >> "$GITHUB_OUTPUT"

    build:
        name: Build
        runs-on: ubuntu-latest
        needs:
            - calculate-version

        permissions:
            contents: read

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - name: Validate Gradle wrapper
              uses: gradle/actions/wrapper-validation@v4

            - name: Build
              run: ./gradlew clean assemble --stacktrace -Pbase_version=${{ needs.calculate-version.outputs.version }}
              env:
                  PACKAGES_TOKEN: ${{ secrets.SHARED_PACKAGES_READ_TOKEN }}

    test:
        name: Test
        runs-on: ubuntu-latest
        needs:
            - calculate-version

        services:
            oracle:
                image: gvenzl/oracle-xe:18.4.0
                ports:
                    - 1521:1521
                env:
                    ORACLE_PASSWORD: MATRIKKELADM
                    APP_USER: SKIF_DEV
                    APP_USER_PASSWORD: SKIF_DEV
                    ORACLE_DATABASE: XEPDB1
                options: >-
                    --health-cmd healthcheck.sh
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 10

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - name: Validate Gradle wrapper
              uses: gradle/actions/wrapper-validation@v4

            - name: Initialize database
              run: ./gradlew dbInit --stacktrace
                  -Pbase_version=${{ needs.calculate-version.outputs.version }}
                  -Pdb_jdbc_url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
                  -Pdb_username=SKIF_DEV
                  -Pdb_password=SKIF_DEV
                  -Padmin_db_username=SYSTEM
                  -Padmin_db_password=MATRIKKELADM
                  -Pdb_dataroot_dir=/opt/oracle/oradata

            - name: Run tests
              run: ./gradlew check --continue --stacktrace
                       -Pbase_version=${{ needs.calculate-version.outputs.version }}
                       -Pdb_jdbc_url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
                       -Pdb_username=SKIF_DEV
                       -Pdb_password=SKIF_DEV
                       -Padmin_db_username=SYSTEM
                       -Padmin_db_password=MATRIKKELADM
                       -Pdb_dataroot_dir=/opt/oracle/oradata
              env:
                  PACKAGES_TOKEN: ${{ secrets.SHARED_PACKAGES_READ_TOKEN }}

            - name: Publish Test Report
              if: always()
              uses: mikepenz/action-junit-report@v5
              with:
                  report_paths: '**/testng-results.xml'
                  check_name: Test rapport
                  annotate_only: true
                  detailed_summary: true

    publish:
        name: Publish to GitHub Packages
        runs-on: ubuntu-latest
        needs:
            - build
            - test
            - calculate-version
        #if: github.ref_name == 'trunk' && github.event_name != 'pull_request'

        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - name: Publish to GitHub Packages
              run: ./gradlew publish --stacktrace -Pbase_version=${{ needs.calculate-version.outputs.version }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PACKAGES_TOKEN: ${{ secrets.SHARED_PACKAGES_READ_TOKEN }}
